<?

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : sender.proto
 */


/**
 * Protobuf enum : SenderType
 */
class SenderType extends \Protobuf\Enum
{

    /**
     * UNKNOWN = 0
     */
    const UNKNOWN_VALUE = 0;

    /**
     * CLIENT = 1
     */
    const CLIENT_VALUE = 1;

    /**
     * BACKEND = 2
     */
    const BACKEND_VALUE = 2;

    /**
     * @var \Bitrix\Pull\Protobuf\SenderType
     */
    protected static $UNKNOWN = null;

    /**
     * @var \Bitrix\Pull\Protobuf\SenderType
     */
    protected static $CLIENT = null;

    /**
     * @var \Bitrix\Pull\Protobuf\SenderType
     */
    protected static $BACKEND = null;

    /**
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function UNKNOWN()
    {
        if (self::$UNKNOWN !== null) {
            return self::$UNKNOWN;
        }

        return self::$UNKNOWN = new self('UNKNOWN', self::UNKNOWN_VALUE);
    }

    /**
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function CLIENT()
    {
        if (self::$CLIENT !== null) {
            return self::$CLIENT;
        }

        return self::$CLIENT = new self('CLIENT', self::CLIENT_VALUE);
    }

    /**
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function BACKEND()
    {
        if (self::$BACKEND !== null) {
            return self::$BACKEND;
        }

        return self::$BACKEND = new self('BACKEND', self::BACKEND_VALUE);
    }

    /**
     * @param int $value
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::UNKNOWN();
            case 1: return self::CLIENT();
            case 2: return self::BACKEND();
            default: return null;
        }
    }


}

