<?
$DB->Query("DELETE FROM b_event_type WHERE EVENT_NAME = 'BIZPROC_MAIL_TEMPLATE' OR EVENT_NAME = 'BIZPROC_HTML_MAIL_TEMPLATE'");
$DB->Query("DELETE FROM b_event_message WHERE EVENT_NAME = 'BIZPROC_MAIL_TEMPLATE' OR EVENT_NAME = 'BIZPROC_HTML_MAIL_TEMPLATE'");
?>