export const PopupType = Object.freeze({
	userProfile: 'im-user-settings-popup',
	userStatus: 'im-user-status-popup',
	backgroundSelect: 'im-background-select-popup',
	recentContextMenu: 'im-recent-context-menu',
	recentHeaderMenu: 'im-recent-header-menu',
	createChatMenu: 'im-create-chat-menu',
	dialogMessageMenu: 'bx-im-message-context-menu',
	dialogAvatarMenu: 'bx-im-avatar-context-menu',
	dialogReactionUsers: 'bx-im-message-reaction-users',
	dialogReadUsers: 'bx-im-dialog-read-users',
	createChatManageUsersMenu: 'im-content-create-chat-manage-users',
	createChatManageUiMenu: 'im-content-create-chat-manage-ui',
	createChatCanPostMenu: 'im-content-create-chat-can-post',
	messageBaseFileMenu: 'im-message-base-file-context-menu',
});
