<?
global $MESS;
$MESS["SALE_RBK_SHOULD_PAY"] = "Amount to be paid";
$MESS["SALE_RBK_DESC_SHOULD_PAY"] = "";
$MESS["SALE_RBK_CURRENCY"] = "Currency";
$MESS["SALE_RBK_DESC_CURRENCY"] = "";
$MESS["SALE_RBK_SERVICE_NAME"] = "Product description";
$MESS["SALE_RBK_DESC_SERVICE_NAME"] = "Description of product to be purchased";
$MESS["SALE_RBK_ORDER_ID"] = "Order ID";
$MESS["SALE_RBK_DESC_ORDER_ID"] = "Order ID from your Internet store";
$MESS["SALE_RBK_ESHOP_ID"] = "Eshop ID in RBK Money";
$MESS["SALE_RBK_DESC_ESHOP_ID"] = "";
$MESS["SALE_RBK_SUCCESS_URL"] = "Contact address for successful payment";
$MESS["SALE_RBK_DESC_SUCCESS_URL"] = "URL script (on seller’s website) for processing notification of successful payment";
$MESS["SALE_RBK_FAIL_URL"] = "Contact address if error in payment";
$MESS["SALE_RBK_DESC_FAIL_URL"] = "URL (on seller’s website) for redirecting buyer in case of unsuccessful payment";
$MESS["SALE_RBK_SECRET_KEY"] = "Seller’s code word";
$MESS["SALE_RBK_DESC_SECRET_KEY"] = " The code field (shared secret) is defined in the process of concluding an agreement for the reception of payment and serves as the connection manager";
$MESS["SALE_RBK_PAY_BUTTON"] = " Payment button name";
$MESS["SALE_RBK_DESC_PAY_BUTTON"] = "";
$MESS["SALE_RBK_USER_FIELD_1"] = " Additional parameter 1";
$MESS["SALE_RBK_DESC_USER_FIELD_1"] = " This is stored with other payer data and is returned upon notification of payment";
$MESS["SALE_RBK_USER_FIELD_2"] = " Additional parameter 2";
$MESS["SALE_RBK_DESC_USER_FIELD_2"] = " This is stored with other payer data and returns upon notification of payment";
$MESS["SALE_RBK_USER_FIELD_3"] = "Additional parameter 3";
$MESS["SALE_RBK_DESC_USER_FIELD_3"] = " This is stored with other payer data and returns upon notification of payment";
$MESS["SALE_RBK_F_NAME"] = "User name";
$MESS["SALE_RBK_DESC_F_NAME"] = "";
$MESS["SALE_RBK_S_NAME"] = "User last name";
$MESS["SALE_RBK_DESC_S_NAME"] = "";
$MESS["SALE_RBK_EMAIL"] = "Email address";
$MESS["SALE_RBK_DESC_EMAIL"] = "";
$MESS["SALE_RBK_ACTION_TYPE"] = "Type (left blank by default)";
$MESS["SALE_RBK_DESC_ACTION_TYPE"] = "Page of payment type on site Robokassa (User immediately transferred to the given type of page): <br/>Payment with Rbk Money  – inner or rbkmoney<br/> Visa/MasterCard — bankcard<br/>electronic payment systems – exchangers <br/>payment terminals -  terminals<br/>RBK Money prepaid- prepaidcard<br/>Russia Post — postrus<br/>Mobile Retail Outlets — mobilestores<br/>Wire transfer services — transfers<br/>Internet banking – ibank<br/>Bank transfers — sberbank<br/>Svyaznoy Retail — svyaznoy<br/>Euroset – euroset<br/>Contact payment system — contact<br/>MTS — mts<br/>Kassa Uralsib — uralsib<br/>HandyBank — handybank<br/>Ocean Bank — ocean<br/>Uralsib Internet bank — ibankuralsib";
?>