export type ProductOption = {
	isNew: boolean,
	isSimpleModel: boolean,
	currency: string,
	iblockId?: number,
	productId?: number,
	offerId?: number,
	basePriceId?: number,
	detailPath?: string,
	isSaveable: boolean,
	pricePrecision: number,
	saveableFields: [],
	fields: {},
	storeMap: {},
	isStoreCollectable: boolean,
	skuTree: {},
	imageInfo: {},
	productType?: number,
}