insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (68, 'ru', 'Широкая улыбка') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (69, 'ru', 'С улыбкой') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (70, 'ru', 'Печально') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (71, 'ru', 'Удивленно') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (72, 'ru', 'Здорово') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (73, 'ru', 'Поцелуй') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (74, 'ru', 'Смущенно') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (75, 'ru', 'Очень грустно') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (76, 'ru', 'Со злостью') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (77, 'ru', 'Шутливо') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (78, 'ru', 'Восклицание') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (79, 'ru', 'Вопрос') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (80, 'ru', 'Идея') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (81, 'ru', 'Нет слов') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (82, 'ru', 'Озадаченно') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (83, 'ru', 'Заметка') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (84, 'ru', 'Направление') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (85, 'ru', 'Идея') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (86, 'ru', 'Внимание') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (87, 'ru', 'Вопрос') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (88, 'ru', 'Плохо') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (89, 'ru', 'Хорошо') ;