<?php
$subscribe_default_option = [
	'allow_anonymous' => 'Y',
	'show_auth_links' => 'Y',
	'subscribe_section' => '#SITE_DIR#about/',
	'posting_interval' => '20',
	'default_from' => '',
	'default_to' => '',
	'posting_charset' => 'Windows-1251,ISO-8859-1,UTF-8',
	'allow_8bit_chars' => 'N',
	'attach_images' => 'N',
	'subscribe_confirm_period' => '60',
	'subscribe_auto_method' => 'agent',
	'subscribe_max_emails_per_hit' => '5',
	'subscribe_template_method' => 'agent',
	'subscribe_template_interval' => '60',
	'max_bcc_count' => '0',
	'mail_additional_parameters' => '',
	'max_file_size' => '0',
	'max_files_size' => '0',
];
