<?
global $MESS;

$MESS["CHRP_SHOULD_PAY"] = "Amount to be paid";
$MESS["CHRP_DESC_SHOULD_PAY"] = "";
$MESS["CHRP_PRODUCT_ID"] = "Product code";
$MESS["CHRP_DESC_PRODUCT_ID"] = "Unique code of product or server on Chronopay";
$MESS["CHRP_PRODUCT_NAME"] = "Product name";
$MESS["CHRP_DESC_PRODUCT_NAME"] = "Name of product for purchase";
$MESS["CHRP_ORDER_ID"] = "Order number";
$MESS["CHRP_DESC_ORDER_ID"] = "Order number in you Internet store";
$MESS["CHRP_CB_URL"] = "Contact address for payment notification";
$MESS["CHRP_DESC_CB_URL"] = "URL script (on seller’s website) for notification of payment result";
$MESS["CHRP_DECLINE_URL"] = "Contact address in case of error in payment";
$MESS["CHRP_DESC_DECLINE_URL"] = "URL (on seller’s website) for redirecting buyer in case of unsuccessful payment";
$MESS["CHRP_SUCCESS_URL"] = "Contact address for successful payment";
$MESS["CHRP_DESC_SUCCESS_URL"] = "URL (on seller’s website) for redirecting buyer after successful purchase";
$MESS["CHRP_SHARED"] = "Seller’s code word";
$MESS["CHRP_DESC_SHARED"] = "The code field (shared secret) is defined in the process of concluding an agreement for the reception of payment and serves as the connection manager";
$MESS["CHRP_YANDEX_FORWARD"] = "Redirecting to the Yandex payment system";
$MESS["CHRP_DESC_YANDEX_FORWARD"] = "Indicate a non-empty value for automatic forwarding to the Yandex payment system";
$MESS["CHRP_WEBMONEY_FORWARD"] = "Forwarding to the WebMoney payment system";
$MESS["CHRP_DESC_WEBMONEY_FORWARD"] = "Provide  a non-empty value for automatic forwarding to the WebMoney payment system";
$MESS["CHRP_QIWI_FORWARD"] = "Redirecting to the Qiwi payment system";
$MESS["CHRP_DESC_QIWI_FORWARD"] = "Provide a non-empty value for automatic forwarding to the Qiwi payment system";
$MESS["CHRP_PAY_BUTTON"] = "Payment button name";
$MESS["CHRP_DESC_PAY_BUTTON"] = "";
$MESS["CHRP_CS2"] = "Additional parameter 1";
$MESS["CHRP_DESC_CS2"] = "This is stored with other payer data and is returned upon notification of payment";
$MESS["CHRP_CS3"] = "Additional parameter 2";
$MESS["CHRP_DESC_CS3"] = "This is stored with other payer data and returns upon notification of payment";
$MESS["CHRP_LANGUAGE"] = "Interface language for Chronopay form";
$MESS["CHRP_DESC_LANGUAGE"] = "Possible values: En – English (default); Ru – Russian; Nl – Dutch; Es - Spanish";
$MESS["CHRP_F_NAME"] = "User name";
$MESS["CHRP_DESC_F_NAME"] = "";
$MESS["CHRP_S_NAME"] = "Last name of user";
$MESS["CHRP_DESC_S_NAME"] = "";
$MESS["CHRP_STREET"] = "Street address";
$MESS["CHRP_DESC_STREET"] = "";
$MESS["CHRP_CITY"] = "City";
$MESS["CHRP_DESC_CITY"] = "";
$MESS["CHRP_STATE"] = "State";
$MESS["CHRP_DESC_STATE"] = "USA only";
$MESS["CHRP_ZIP"] = "ZIP or Postal code";
$MESS["CHRP_DESC_ZIP"] = "";
$MESS["CHRP_COUNTRY"] = "Country";
$MESS["CHRP_DESC_COUNTRY"] = "Two-letter code (<a href='http://www.iso.org/iso/country_codes/iso_3166_code_lists/english_country_names_and_code_elements.htm#lr'>ISO 3166-1 alpha-2</a>)";
$MESS["CHRP_PHONE"] = "Telephone";
$MESS["CHRP_DESC_PHONE"] = "Telephone with country code";
$MESS["CHRP_EMAIL"] = "Email address";
$MESS["CHRP_DESC_EMAIL"] = "";
$MESS["CHRP_ORDER_UNIQ"] = "Implement monitoring functionality for uniqueness of order payment";
$MESS["CHRP_DESC_ORDER_UNIQ"] = "Provide a non-empty value for using this function";
?>