<?
$DB->Query("DELETE FROM b_event_type WHERE EVENT_NAME in (
	'SONET_NEW_MESSAGE', 
	'SONET_INVITE_FRIEND',
	'SONET_INVITE_GROUP',
	'SONET_AGREE_FRIEND',
	'SONET_BAN_FRIEND',
	'SONET_NEW_EVENT_GROUP',
	'SONET_NEW_EVENT_USER',
	'SONET_NEW_EVENT',
	'SONET_REQUEST_GROUP'	
	)");

$DB->Query("DELETE FROM b_event_message WHERE EVENT_NAME in (
	'SONET_NEW_MESSAGE', 
	'SONET_INVITE_FRIEND',
	'SONET_INVITE_GROUP',
	'SONET_AGREE_FRIEND',
	'SONET_BAN_FRIEND',
	'SONET_NEW_EVENT_GROUP',
	'SONET_NEW_EVENT_USER',
	'SONET_NEW_EVENT',
	'SONET_REQUEST_GROUP'
	)");
?>