CREATE TABLE b_ui_entity_editor_config
(
	ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CATEGORY VARCHAR(20) NOT NULL,
	ENTITY_TYPE_ID VARCHAR(60) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONFIG TEXT NOT NULL,
	COMMON VARCHAR(1) NOT NULL,
	PRIMARY KEY (ID),
	INDEX ENTITY_TYPE_ID (ENTITY_TYPE_ID),
	INDEX CATEGORY (CATEGORY)
);

CREATE TABLE b_ui_entity_editor_config_ac
(
	ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	ACCESS_CODE VARCHAR(10) NOT NULL,
	CONFIG_ID INTEGER(10) NOT NULL,
	PRIMARY KEY (ID),
	INDEX ACCESS_CODE (ACCESS_CODE),
	INDEX CONFIG_ID (CONFIG_ID)
);

CREATE TABLE b_ui_file_uploader_temp_file
(
	ID INT NOT NULL AUTO_INCREMENT,
	GUID CHAR(36) NOT NULL,
	FILE_ID INT,
	FILENAME VARCHAR(255) NOT NULL,
	SIZE BIGINT NOT NULL,
	PATH VARCHAR(255) NOT NULL,
	MIMETYPE VARCHAR(255) NOT NULL,
	RECEIVED_SIZE BIGINT NOT NULL DEFAULT 0,
	WIDTH INT NOT NULL DEFAULT 0,
	HEIGHT INT NOT NULL DEFAULT 0,
	BUCKET_ID INT,
	MODULE_ID VARCHAR(50) NOT NULL,
	CONTROLLER VARCHAR(255) NOT NULL,
	CLOUD TINYINT(1) NOT NULL DEFAULT 0,
	UPLOADED TINYINT(1) NOT NULL DEFAULT 0,
	DELETED TINYINT(1) NOT NULL DEFAULT 0,
	CREATED_BY INT NOT NULL DEFAULT 0,
	CREATED_AT DATETIME NOT NULL,

	INDEX IX_B_UI_UPLOADER_FILE_ID(FILE_ID),
	INDEX IX_B_UI_UPLOADER_CREATED_AT(CREATED_AT),
	UNIQUE INDEX IX_B_UI_UPLOADER_GUID(GUID),
	PRIMARY KEY (ID)
);
