CREATE TABLE b_ui_entity_editor_config
(
	ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CATEGORY VARCHAR(20) NOT NULL,
	ENTITY_TYPE_ID VARCHAR(60) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONFIG TEXT NOT NULL,
	COMMON VARCHAR(1) NOT NULL,
	PRIMARY KEY (ID),
	INDEX ENTITY_TYPE_ID (ENTITY_TYPE_ID),
	INDEX CATEGORY (CATEGORY)
);

CREATE TABLE b_ui_entity_editor_config_ac
(
	ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	ACCESS_CODE VARCHAR(10) NOT NULL,
	CONFIG_ID INTEGER(10) NOT NULL,
	PRIMARY KEY (ID),
	INDEX ACCESS_CODE (ACCESS_CODE),
	INDEX CONFIG_ID (CONFIG_ID)
);
