<?
$nameUTF = array(
	"CommerceInfo" => "КоммерческаяИнформация",
	"Company" => "Контрагент",
	"Catalog" => "Каталог",
	"Product" => "Товар",
	"ID" => "Идентификатор",
	"Name" => "Наименование",
	"DisplayName" => "ОтображаемоеНаименование",
	"Amount" => "Количество",
	"Price" => "Цена",
	"Property" => "Свойство",
	"Description" => "Описание",
	"Unit" => "Единица",
	"DataType" => "ТипДанных",
	"DisplayOnSite" => "Отображается",
	"Multiple" => "Множественность",
	"DefaultValue" => "ЗначениеПоУмолчанию",
	"PropertyReference" => "СсылкаНаСвойство",
	"CatalogID" => "ИдентификаторКаталога",
	"IdInCatalog" => "ИдентификаторВКаталоге",
	"PropertyId" => "ИдентификаторСвойства",
	"PropertyVariant" => "ВариантСвойства",
	"ParentCategory" => "Родитель",
	"Category" => "Группа",
	"OffersList" => "ПакетПредложений",
	"Currency" => "Валюта",
	"Offer" => "Предложение",
	"ProductId" => "ИдентификаторТовара",
	"PropertyValue" => "ЗначениеСвойства",
	"Value" => "Значение",
	"CategoryReference" => "СсылкаНаГруппу",
	"CommerceInfoVersion" => "ВерсияСхемы",
	"Yandex" => "yml_catalog"
);
?>