<?if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();
$arTooltips = array(
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"IBLOCK_ID" => GetMessage("IBLOCK_ID_TIP"),
	"ELEMENT_SORT_FIELD" => GetMessage("ELEMENT_SORT_FIELD_TIP"),
	"ELEMENT_SORT_ORDER" => GetMessage("ELEMENT_SORT_ORDER_TIP"),
	"SECTION_URL" => GetMessage("SECTION_URL_TIP"),
	"DETAIL_URL" => GetMessage("DETAIL_URL_TIP"),
	"BASKET_URL" => GetMessage("BASKET_URL_TIP"),
	"ACTION_VARIABLE" => GetMessage("ACTION_VARIABLE_TIP"),
	"PRODUCT_ID_VARIABLE" => GetMessage("PRODUCT_ID_VARIABLE_TIP"),
	"SECTION_ID_VARIABLE" => GetMessage("SECTION_ID_VARIABLE_TIP"),
	"DISPLAY_COMPARE" => GetMessage("DISPLAY_COMPARE_TIP"),
	"ELEMENT_COUNT" => GetMessage("ELEMENT_COUNT_TIP"),
	"LINE_ELEMENT_COUNT" => GetMessage("LINE_ELEMENT_COUNT_TIP"),
	"PROPERTY_CODE" => GetMessage("PROPERTY_CODE_TIP"),
	"PRICE_CODE" => GetMessage("PRICE_CODE_TIP"),
	"USE_PRICE_COUNT" => GetMessage("USE_PRICE_COUNT_TIP"),
	"SHOW_PRICE_COUNT" => GetMessage("SHOW_PRICE_COUNT_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"PRICE_VAT_INCLUDE" => GetMessage("PRICE_VAT_INCLUDE_TIP"),
);
?>