<?php
$iblock_default_option = [
	'use_htmledit' => 'Y',
	'show_xml_id' => 'N',
	'path2rss' => '/upload/',
	'combined_list_mode' => 'N',
	'iblock_menu_max_sections' => '50',
	'list_image_size' => '50',
	'detail_image_size' => '200',
	'event_log_iblock' => 'Y',
	'num_catalog_levels' => '3',
	'seo_max_stores' => '20',
	'custom_edit_form_use_property_id' => 'Y',
	'list_full_date_edit' => 'N',
	'property_features_enabled' => 'Y',
	'iblock_activity_dates' => '',
	'iblock_activity_dates_period' => '86400',
	'excel_export_rights' => 'N',
	'change_user_by_group_active_modify' => 'N',
];
