<?php
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_DESCRIPTION"] = "Услугу предоставляет сервис онлайн-платежей <b>&laquo;Яндекс.Касса&raquo;</b>.<br /><br />Сумма к оплате по счету: ";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_WARNING_RETURN"] = "<b>Обратите внимание:</b> если вы откажетесь от покупки, для возврата денег вам придется обратиться в магазин.";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_BUTTON_PAID"] = "Оплатить";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_PROMT"]="Вы хотите оплатить через систему <b>www.assist.ru</b>.";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ACCOUNT_NO"]="Cчет №";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ORDER_FROM"]=" от ";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ORDER_SUM"]="Сумма к оплате по счету:";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ACTION"]="Оплатить";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES_TITLE"]="Обработка заказа";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES"]="Магазин оставляет за собой право дополнительно произвести телефонную авторизацию платежа. Все заказы обрабатываются не в автоматическом режиме: по рабочим дням с 10:00 до 18:00 (московское время).<br><br>В связи с усилением борьбы с мошенничеством международными платежными системами транзакции по картам Visa и Eurocard/Mastercard без заполнения поля, предназначенного для указания CVV2/CVC2 (CVV2 или CVC2 - уникальное контрольное число, нанесенное на обратной стороне карты после ее номера), данными платежными системами приниматься к обработке не будут.<br><br>В системе <a href=\"http://www.assist.ru/\">Ассист</a> безопасность платежей обеспечивается использованием SSL протокола для передачи конфиденциальной информации от клиента на сервер <a href=\"http://www.assist.ru/\">системы Ассист</a> для дальнейшей обработки.<br><br>Дальнейшая передача информации осуществляется по закрытым банковским сетям, взлом которых практически невозможен.<br><br>Обработка полученных конфиденциальных данных клиента  производится в процессинговом центре <a href=\"http://www.alfabank.ru/\">КБ \"Альфа-Банк\"</a>. Таким образом, никто, даже продавец не может получить персональные и банковские данные клиента.<br><br>";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES_TITLE1"]="Безопасность передаваемой информации";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES1"]="Для защиты информации от несанкционированного доступа на этапе передачи от клиента на сервер системы используется протокол SSL 3.0, сертификат сервера (128 bit) выдан компанией <a href=\"https://www.thawte.com\">Thawte</a> - признанным центром выдачи цифровых сертификатов.<br><br>Вы можете <a href=\"https://sealinfo.thawte.com/thawtesplash?form_file=fdf/thawtesplash.fdf&dn=WWW.ASSIST.RU&lang=en\">проверить подлинность сертификата</a> сервера Ассист.";