export const EventTypes = Object.freeze({
	showLoader: 'socialnetwork:spacesList:showLoader',
	hideLoader: 'socialnetwork:spacesList:hideLoader',
	tryToLoadSpacesIfHasNoScrollbar: 'socialnetwork:spacesList:tryToLoadSpacesIfHasNoScrollbar',
	spaceListScroll: 'socialnetwork:spacesList:onScroll',
	spaceListShown: 'socialnetwork:spacesList:onShown',
	showUpperSpaceAddForm: 'socialnetwork:spacesList:showUpperSpaceAddForm',
	showBtnToggleBlock: 'socialnetwork:spacesList:showBtnToggleBlock',
	hideSpaceAddForm: 'socialnetwork:spacesList:hideSpaceAddForm',
	updateCounters: 'socialnetwork:spacesList:updateCounters',
	changeSpace: 'socialnetwork:spacesList:changeSpace',
	changeUserRole: 'socialnetwork:spacesList:changeUserRole',
	changeSubscription: 'socialnetwork:spacesList:changeSubscription',
	pinChanged: 'socialnetwork:spacesList:pinChanged',
	changeSpaceListState: 'socialnetwork:spacesList:changeSpaceListState',
	recentActivityUpdate: 'socialnetwork:spacesList:recentActivityUpdate',
	recentActivityDelete: 'socialnetwork:spacesList:recentActivityDelete',
	recentActivityRemoveFromSpace: 'socialnetwork:spacesList:recentActivityRemoveFromSpace',
	openSpaceFromContextMenu: 'socialnetwork:spacesList:openSpaceFromContextMenu',
	changeMode: 'socialnetwork:spacesList:changeMode',
});
