<?php
$perfmon_default_option = [
	'max_graph_width' => 1024,
	'max_graph_height' => 768,
	'max_display_url' => 80,
	'sql_log' => 'Y',
	'slow_sql_log' => 'N',
	'slow_sql_time' => 0.1,
	'warning_log' => 'N',
	'sql_backtrace' => 'N',
	'cache_log' => 'N',
	'large_cache_log' => 'N',
	'large_cache_size' => 1024,
	'test_threads_from' => 2,
	'test_threads_to' => 32,
	'test_threads_step' => 2,
	'test_server_name' => $_SERVER['HTTP_HOST'],
	'test_threads_duration' => 10,
	'enable_tablet_generator' => 'N',
	'tablet_short_aliases' => 'Y',
	'tablet_object_settings' => 'N',
	'tablet_use_map_index' => 'N',
	'tablet_validation_closure' => 'Y',
];
