<?
global $MESS;

$MESS["CHRP_SHOULD_PAY"] = "Сумма к оплате";
$MESS["CHRP_DESC_SHOULD_PAY"] = "";
$MESS["CHRP_PRODUCT_ID"] = "Код товара";
$MESS["CHRP_DESC_PRODUCT_ID"] = "Уникальный код товара или услуги на сайте Chronopay";
$MESS["CHRP_PRODUCT_NAME"] = "Наименование товара";
$MESS["CHRP_DESC_PRODUCT_NAME"] = "Наименование товара  к оплате";
$MESS["CHRP_ORDER_ID"] = "Номер заказа";
$MESS["CHRP_DESC_ORDER_ID"] = "Номер заказа в вашем Интернет-магазине";
$MESS["CHRP_CB_URL"] = "Адрес для уведомлений об оплате";
$MESS["CHRP_DESC_CB_URL"] = "URL скрипта (на веб-сайте продавца) обрабатывающего оповещения о результате платежа";
$MESS["CHRP_DECLINE_URL"] = "Адрес при ошибке оплаты";
$MESS["CHRP_DESC_DECLINE_URL"] = "URL (на веб-сайте продавца) для перенаправления плательщика при неуспешном платеже";
$MESS["CHRP_SUCCESS_URL"] = "Адрес при успешной оплате";
$MESS["CHRP_DESC_SUCCESS_URL"] = "URL (на веб-сайте продавца) для перенаправления плательщика при успешном платеже";
$MESS["CHRP_SHARED"] = "Кодовое слово продавца";
$MESS["CHRP_DESC_SHARED"] = "Кодовое поле (shared secret) определяется в процессе заключения договоренности по активации функционала приема платежей и предоставляется менеджером по подключению";
$MESS["CHRP_YANDEX_FORWARD"] = "Перенаправление в платежную систему Yandex";
$MESS["CHRP_DESC_YANDEX_FORWARD"] = "Укажите непустое значение для автоматического перенаправления в платежную систему Yandex";
$MESS["CHRP_WEBMONEY_FORWARD"] = "Перенаправление в платежную систему WebMoney";
$MESS["CHRP_DESC_WEBMONEY_FORWARD"] = "Укажите непустое значение для автоматического перенаправления в платежную систему WebMoney";
$MESS["CHRP_QIWI_FORWARD"] = "Перенаправление в платежную систему Qiwi";
$MESS["CHRP_DESC_QIWI_FORWARD"] = "Укажите непустое значение для автоматического перенаправления в платежную систему Qiwi";
$MESS["CHRP_PAY_BUTTON"] = "Название кнопки оплаты";
$MESS["CHRP_DESC_PAY_BUTTON"] = "";
$MESS["CHRP_CS2"] = "Дополнительный параметр 1";
$MESS["CHRP_DESC_CS2"] = "Хранится вместе с прочими данными плательщика и возвращаются при оповещении о платеже и выгрузке данных";
$MESS["CHRP_CS3"] = "Дополнительный параметр 2";
$MESS["CHRP_DESC_CS3"] = "Хранится вместе с прочими данными плательщика и возвращаются при оповещении о платеже и выгрузке данных";
$MESS["CHRP_LANGUAGE"] = "Язык интерфейса формы Chronopay";
$MESS["CHRP_DESC_LANGUAGE"] = "Возможные значения: En – английский (по умолчанию); Ru – русский;	Nl – голландский; Es - испанский;";
$MESS["CHRP_F_NAME"] = "Имя пользователя";
$MESS["CHRP_DESC_F_NAME"] = "";
$MESS["CHRP_S_NAME"] = "Фамилия пользователя";
$MESS["CHRP_DESC_S_NAME"] = "";
$MESS["CHRP_STREET"] = "Улица проживания";
$MESS["CHRP_DESC_STREET"] = "";
$MESS["CHRP_CITY"] = "Город проживания";
$MESS["CHRP_DESC_CITY"] = "";
$MESS["CHRP_STATE"] = "Штат проживания";
$MESS["CHRP_DESC_STATE"] = "только для США";
$MESS["CHRP_ZIP"] = "Почтовый индекс";
$MESS["CHRP_DESC_ZIP"] = "";
$MESS["CHRP_COUNTRY"] = "Страна проживания";
$MESS["CHRP_DESC_COUNTRY"] = "2-х буквенный код (<a href='http://www.iso.org/iso/country_codes/iso_3166_code_lists/english_country_names_and_code_elements.htm#lr'>ISO 3166-1 alpha-2</a>)";
$MESS["CHRP_PHONE"] = "Телефон";
$MESS["CHRP_DESC_PHONE"] = "Номер телефона в международном формате";
$MESS["CHRP_EMAIL"] = "Электронная почта";
$MESS["CHRP_DESC_EMAIL"] = "";
$MESS["CHRP_ORDER_UNIQ"] = "Использовать функционал контроля уникальности оплаты заказа";
$MESS["CHRP_DESC_ORDER_UNIQ"] = "Укажите непустое значение для использования данного функционала";
?>