<pre>
Array
(
    [ID] => 33
    [LID] => ru
    [PERSON_TYPE_ID] => 1
    [PAYED] => N
    [DATE_PAYED] => 
    [EMP_PAYED_ID] => 
    [CANCELED] => N
    [DATE_CANCELED] => 
    [EMP_CANCELED_ID] => 
    [REASON_CANCELED] => 
    [STATUS_ID] => F
    [DATE_STATUS] => 11.01.2007 16:44:57
    [PAY_VOUCHER_NUM] => 
    [PAY_VOUCHER_DATE] => 
    [EMP_STATUS_ID] => 10
    [PRICE_DELIVERY] => 0.00
    [ALLOW_DELIVERY] => Y
    [DATE_ALLOW_DELIVERY] => 11.01.2007 16:44:57
    [EMP_ALLOW_DELIVERY_ID] => 10
    [PRICE] => 12450.00
    [CURRENCY] => RUR
    [DISCOUNT_VALUE] => 0.00
    [SUM_PAID] => 0.00
    [USER_ID] => 10
    [PAY_SYSTEM_ID] => 1
    [DELIVERY_ID] => 
    [DATE_INSERT] => 11.01.2007 16:06:08
    [DATE_INSERT_FORMAT] => 11.01.2007 16:06:08
    [DATE_UPDATE] => 12.01.2007 13:01:20
    [USER_DESCRIPTION] => 
    [ADDITIONAL_INFO] => 
    [PS_STATUS] => 
    [PS_STATUS_CODE] => 
    [PS_STATUS_DESCRIPTION] => 
    [PS_STATUS_MESSAGE] => 
    [PS_SUM] => 
    [PS_CURRENCY] => 
    [PS_RESPONSE_DATE] => 
    [COMMENTS] => 
    [TAX_VALUE] => 0.00
    [STAT_GID] => 
    [RECURRING_ID] => 
    [RECOUNT_FLAG] => Y
    [USER_LOGIN] => anton
    [USER_NAME] => Anton Ezhkov
    [USER_LAST_NAME] => Ezhkov
    [USER_EMAIL] => anton@bitrixsoft.ru
    [~ID] => 33
    [~LID] => ru
    [~PERSON_TYPE_ID] => 1
    [~PAYED] => N
    [~DATE_PAYED] => 
    [~EMP_PAYED_ID] => 
    [~CANCELED] => N
    [~DATE_CANCELED] => 
    [~EMP_CANCELED_ID] => 
    [~REASON_CANCELED] => 
    [~STATUS_ID] => F
    [~DATE_STATUS] => 11.01.2007 16:44:57
    [~PAY_VOUCHER_NUM] => 
    [~PAY_VOUCHER_DATE] => 
    [~EMP_STATUS_ID] => 10
    [~PRICE_DELIVERY] => 0.00
    [~ALLOW_DELIVERY] => Y
    [~DATE_ALLOW_DELIVERY] => 11.01.2007 16:44:57
    [~EMP_ALLOW_DELIVERY_ID] => 10
    [~PRICE] => 12450.00
    [~CURRENCY] => RUR
    [~DISCOUNT_VALUE] => 0.00
    [~SUM_PAID] => 0.00
    [~USER_ID] => 10
    [~PAY_SYSTEM_ID] => 1
    [~DELIVERY_ID] => 
    [~DATE_INSERT] => 11.01.2007 16:06:08
    [~DATE_INSERT_FORMAT] => 11.01.2007 16:06:08
    [~DATE_UPDATE] => 12.01.2007 13:01:20
    [~USER_DESCRIPTION] => 
    [~ADDITIONAL_INFO] => 
    [~PS_STATUS] => 
    [~PS_STATUS_CODE] => 
    [~PS_STATUS_DESCRIPTION] => 
    [~PS_STATUS_MESSAGE] => 
    [~PS_SUM] => 
    [~PS_CURRENCY] => 
    [~PS_RESPONSE_DATE] => 
    [~COMMENTS] => 
    [~TAX_VALUE] => 0.00
    [~STAT_GID] => 
    [~RECURRING_ID] => 
    [~RECOUNT_FLAG] => Y
    [~USER_LOGIN] => anton
    [~USER_NAME] => Anton
    [~USER_LAST_NAME] => Ezhkov
    [~USER_EMAIL] => anton@bitrixsoft.ru
    [PRICE_FORMATED] => 12 450.00 р.
    [DISCOUNT_VALUE_FORMATED] => 0.00 р.
    [CAN_CANCEL] => N
    [URL_TO_LIST] => index.php&filter_history=Y&filter=Y&set_filter=Y
    [SITE_ID] => ru
    [STATUS] => Array
        (
            [ID] => F
            [SORT] => 100
            [LID] => ru
            [NAME] => Доставлен
            [DESCRIPTION] => 
        )

    [USER] => Array
        (
            [ID] => 10
            [TIMESTAMP_X] => 11.01.2007 11:00:10
            [LOGIN] => anton
            [PASSWORD] => 4a181673429f0b6abbfd452f0f3b5950
            [CHECKWORD] => h0sG9BJ5
            [ACTIVE] => Y
            [NAME] => Anton
            [LAST_NAME] => Ezhkov
            [EMAIL] => anton@bitrixsoft.ru
            [LAST_LOGIN] => 15.01.2007 16:21:27
            [DATE_REGISTER] => 20.03.2006 15:28:28
            [LID] => ru
            [PERSONAL_PROFESSION] => 
            [PERSONAL_WWW] => http://www.bitrix.ru
            [PERSONAL_ICQ] => 
            [PERSONAL_GENDER] => 
            [PERSONAL_BIRTHDATE] => 
            [PERSONAL_PHOTO] => 3877
            [PERSONAL_PHONE] => 
            [PERSONAL_FAX] => 
            [PERSONAL_MOBILE] => 
            [PERSONAL_PAGER] => 
            [PERSONAL_STREET] => 
            [PERSONAL_MAILBOX] => 
            [PERSONAL_CITY] => 
            [PERSONAL_STATE] => 
            [PERSONAL_ZIP] => 
            [PERSONAL_COUNTRY] => 17
            [PERSONAL_NOTES] => 
            [WORK_COMPANY] => 
            [WORK_DEPARTMENT] => 
            [WORK_POSITION] => 
            [WORK_WWW] => 
            [WORK_PHONE] => 
            [WORK_FAX] => 
            [WORK_PAGER] => 
            [WORK_STREET] => 
            [WORK_MAILBOX] => 
            [WORK_CITY] => 
            [WORK_STATE] => 
            [WORK_ZIP] => 
            [WORK_COUNTRY] => 0
            [WORK_PROFILE] => 
            [WORK_LOGO] => 3876
            [WORK_NOTES] => 
            [ADMIN_NOTES] => 
            [STORED_HASH] => 
            [XML_ID] => 
            [PERSONAL_BIRTHDAY] => 15.06.1984
            [EXTERNAL_AUTH_ID] => 
            [CHECKWORD_TIME] => 2007-01-11 11:00:10
            [SECOND_NAME] => Aleks
            [~ID] => 10
            [~TIMESTAMP_X] => 11.01.2007 11:00:10
            [~LOGIN] => anton
            [~PASSWORD] => 4a181673429f0b6abbfd452f0f3b5950
            [~CHECKWORD] => h0sG9BJ5
            [~ACTIVE] => Y
            [~NAME] => Anton
            [~LAST_NAME] => Ezhkov
            [~EMAIL] => anton@bitrixsoft.ru
            [~LAST_LOGIN] => 15.01.2007 16:21:27
            [~DATE_REGISTER] => 20.03.2006 15:28:28
            [~LID] => ru
            [~PERSONAL_PROFESSION] => 
            [~PERSONAL_WWW] => http://www.bitrix.ru
            [~PERSONAL_ICQ] => 
            [~PERSONAL_GENDER] => 
            [~PERSONAL_BIRTHDATE] => 
            [~PERSONAL_PHOTO] => 3877
            [~PERSONAL_PHONE] => 
            [~PERSONAL_FAX] => 
            [~PERSONAL_MOBILE] => 
            [~PERSONAL_PAGER] => 
            [~PERSONAL_STREET] => 
            [~PERSONAL_MAILBOX] => 
            [~PERSONAL_CITY] => 
            [~PERSONAL_STATE] => 
            [~PERSONAL_ZIP] => 
            [~PERSONAL_COUNTRY] => 17
            [~PERSONAL_NOTES] => 
            [~WORK_COMPANY] => 
            [~WORK_DEPARTMENT] => 
            [~WORK_POSITION] => 
            [~WORK_WWW] => 
            [~WORK_PHONE] => 
            [~WORK_FAX] => 
            [~WORK_PAGER] => 
            [~WORK_STREET] => 
            [~WORK_MAILBOX] => 
            [~WORK_CITY] => 
            [~WORK_STATE] => 
            [~WORK_ZIP] => 
            [~WORK_COUNTRY] => 0
            [~WORK_PROFILE] => 
            [~WORK_LOGO] => 3876
            [~WORK_NOTES] => 
            [~ADMIN_NOTES] => 
            [~STORED_HASH] => 
            [~XML_ID] => 
            [~PERSONAL_BIRTHDAY] => 15.06.1984
            [~EXTERNAL_AUTH_ID] => 
            [~CHECKWORD_TIME] => 2007-01-11 11:00:10
            [~SECOND_NAME] => Aleks
        )

    [PERSON_TYPE] => Array
        (
            [ID] => 1
            [LID] => ru
            [NAME] => Физическое лицо
            [SORT] => 0
        )

    [PAY_SYSTEM] => Array
        (
            [ID] => 1
            [LID] => ru
            [CURRENCY] => RUR
            [NAME] => Наличные
            [ACTIVE] => Y
            [SORT] => 100
            [DESCRIPTION] => 
            [PSA_ID] => 1
            [PSA_NAME] => Наличными курьеру
            [PSA_ACTION_FILE] => c:/projects/siteman/bitrix/modules/sale/payment/cash/payment.php
            [PSA_RESULT_FILE] => 
            [PSA_NEW_WINDOW] => N
            [PSA_PARAMS] => a:0:{}
            [PSA_HAVE_PAYMENT] => Y
            [PSA_HAVE_ACTION] => N
            [PSA_HAVE_RESULT] => N
            [PSA_HAVE_PREPAY] => N
        )

    [CAN_REPAY] => Y
    [BASKET] => Array
        (
            [0] => Array
                (
                    [ID] => 51
                    [DETAIL_PAGE_URL] => 
                    [NAME] => Битрикс: Управление сайтом - Малый бизнес (MySQL/OracleXE/MS SQL Express)
                    [NOTES] => 
                    [QUANTITY] => 1
                    [PRICE] => 12450.00
                    [CURRENCY] => RUR
                    [~ID] => 51
                    [~DETAIL_PAGE_URL] => 
                    [~NAME] => Битрикс: Управление сайтом - Малый бизнес (MySQL/OracleXE/MS SQL Express)
                    [~NOTES] => 
                    [~QUANTITY] => 1
                    [~PRICE] => 12450.00
                    [~CURRENCY] => RUR
                    [PRICE_FORMATED] => 12 450.00 р.
                )

        )

    [TAX_VALUE_FORMATED] => 0.00 р.
    [PRICE_DELIVERY_FORMATED] => 0.00 р.
)
</pre>