CREATE TABLE IF NOT EXISTS b_b24connector_buttons
(
	ID INT NOT NULL,
	APP_ID INT NOT NULL,
	ADD_DATE DATETIME NOT NULL,
	ADD_BY INT NOT NULL,
	NAME VARCHAR(255) NULL,
	SCRIPT TEXT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_b24connector_button_site
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	BUTTON_ID INT(11) NOT NULL,
	SITE_ID char(2) NOT NULL,
	PRIMARY KEY(ID),
	INDEX IX_BUTTON_ID (BUTTON_ID)
);
