CREATE TABLE IF NOT EXISTS b_b24connector_buttons
(
  ID INT NOT NULL,
  APP_ID INT NOT NULL,
  ADD_DATE DATETIME NOT NULL,
  ADD_BY INT NOT NULL,
  NAME VARCHAR(255) NULL,
  SCRIPT TEXT NULL,
  PRIMARY KEY(ID)
);