<?
$MESS["RAPC_DESC"] = "Confirm your request to connect your Bitrix24 to <b>#SITE_TITLE#</b> to unify all client communication channels inside your CRM.<br /><br />Just click \"Confirm\" to get your site connected. You can manage the connection on the website, or simply delete the autogenerated password here: <a href=\"#AP_LINK#\">Application Passwrods</a>.";
$MESS["RAPC_BTN_AGREE"] = "Confirm";
$MESS["RAPC_BTN_DISAGREE"] = "Cancel";
$MESS["RAPC_ACCESS"] = "The site requests the following permissions:";
?>