<?
$DB->Query("DELETE FROM b_event_type WHERE EVENT_NAME in (
	'NEW_BLOG_MESSAGE', 
	'NEW_BLOG_COMMENT',
	'NEW_BLOG_COMMENT2COMMENT',
	'NEW_BLOG_COMMENT_WITHOUT_TITLE',
	'NEW_BLOG_COMMENT2COMMENT_WITHOUT_TITLE',
	'BLOG_YOU_TO_BLOG',
	'BLOG_USER_TO_YOUR_BLOG',
	'BLOG_YOUR_BLOG_TO_USER',
	'BLOG_BLOG_TO_YOU'
	)");

$DB->Query("DELETE FROM b_event_message WHERE EVENT_NAME in (
	'NEW_BLOG_MESSAGE', 
	'NEW_BLOG_COMMENT',
	'NEW_BLOG_COMMENT2COMMENT',
	'NEW_BLOG_COMMENT_WITHOUT_TITLE',
	'NEW_BLOG_COMMENT2COMMENT_WITHOUT_TITLE',
	'BLOG_YOU_TO_BLOG',
	'BLOG_USER_TO_YOUR_BLOG',
	'BLOG_YOUR_BLOG_TO_USER',
	'BLOG_BLOG_TO_YOU'
	)");
?>