<?
global $MESS;

$MESS["SASP_PROMT"] = "Payment via <b>www.assist.ru</b>.";
$MESS["SASP_ACCOUNT_NO"] = "Account no.";
$MESS["SASP_ORDER_FROM"] = "from ";
$MESS["SASP_ORDER_SUM"] = "Amount due:";
$MESS["SASP_ACTION"] = "Pay";
$MESS["SASP_NOTES_TITLE"] = "Processing";
$MESS["SASP_NOTES"] = "The web shop reserves the right to perform payment authorisation by phone. All orders are processed manually on working days 10:00 - 18:00 MSK.<br><br>Due to intensification of struggle against frauds in payments via Visa and Eurocard/Mastercard, payments without CVV2/CVC2 will fail.<br><br>The <a href=\"http://www.assist.ru/\">Assist</a> system uses SSL to ensure your safety and privacy.<br><br>Further transactions are performed via private banking networks which are absolutely hacker safe.<br><br>All confidential data is processed in the <a href=\"http://www.alfabank.ru/\">Alpha Bank</a> processing center. This means that no one including seller will see your peronal and banking details.<br><br>";
$MESS["SASP_NOTES_TITLE1"] = "Information security";
$MESS["SASP_NOTES1"] = "We use the SSL 3.0 protocol to secure information transmitted from client to our server. The certificate (128 bit) is issued by <a href=\"https://www.thawte.com\">Thawte</a> - the leader in issuing digital certificates.<br><br>You can <a href=\"https://sealinfo.thawte.com/thawtesplash?form_file=fdf/thawtesplash.fdf&dn=WWW.ASSIST.RU&lang=en\">check identity of our certificate</a>.";
$MESS["SASP_AS000"] = "AUTHORISATION WAS SUCCESSFUL";
$MESS["SASP_AS001"] = "AUTHORISATION WAS SUCCESSFUL (WITH CVC2)";
$MESS["SASP_AS010"] = "PRE-AUTHORISATION WAS SUCCESSFUL";
$MESS["SASP_AS011"] = "PRE-AUTHORISATION WAS SUCCESSFUL (WITH CVC2)";
$MESS["SASP_AS020"] = "POST-AUTHORISATION WAS SUCCESSFUL";
$MESS["SASP_AS100"] = "AUTHORISATION DECLINED";
$MESS["SASP_AS101"] = "AUTHORISATION DECLINED. Incorrect number";
$MESS["SASP_AS102"] = "AUTHORISATION DECLINED. You do not have sufficient funds";
$MESS["SASP_AS104"] = "AUTHORISATION DECLINED. Incorrect expiration date";
$MESS["SASP_AS105"] = "AUTHORISATION DECLINED. Limit exceeded";
$MESS["SASP_AS106"] = "AUTHORISATION DECLINED. Incorrect PIN";
$MESS["SASP_AS107"] = "AUTHORISATION DECLINED. Error receiving data";
$MESS["SASP_AS108"] = "AUTHORISATION DECLINED. Potential fraud";
$MESS["SASP_AS109"] = "AUTHORISATION DECLINED. Assist operations limit exceeded";
$MESS["SASP_AS200"] = "REPEAT AUTHORISATION";
$MESS["SASP_AS300"] = "AUTHORISING. PLEASE WAIT";
$MESS["SASP_AS400"] = "NO PAYMENT WITH SUCH PARAMETERS EXIST";
$MESS["SASP_AS998"] = "SYSTEM ERROR. PLEASE CONTACT ASSIST";
$MESS["SALE_ASSIST_DESCRIPTION"] = "<a href=\"http://www.assist.ru\" target=\"_blank\">http://www.assist.ru</a>";
$MESS["SALE_ASSIST_SHOP_IDP_NAME"] = "Shop ID";
$MESS["SALE_ASSIST_SHOP_IDP_DESCR"] = "Shop ID obtained from Assist.ru";
$MESS["SALE_ASSIST_SHOP_LOGIN_NAME"] = "Login";
$MESS["SALE_ASSIST_SHOP_LOGIN_DESCR"] = "Login obtained from Assist.ru";
$MESS["SALE_ASSIST_SHOP_PASSWORD_NAME"] = "Password";
$MESS["SALE_ASSIST_SHOP_PASSWORD_DESCR"] = "Password obtained from Assist.ru";
$MESS["SALE_ASSIST_FIRST_NAME_NAME"] = "Customer name";
$MESS["SALE_ASSIST_LAST_NAME_NAME"] = "Customer last name";
$MESS["SALE_ASSIST_DEMO_NAME"] = "Test mode";
$MESS["SALE_ASSIST_EMAIL_NAME"] = "Customer e-mail";
$MESS["SALE_ASSIST_PHONE_NAME"] = "Customer phone";
$MESS["SALE_ASSIST_ADDRESS_NAME"] = "Customer address";
$MESS["SALE_ASSIST_MIDDLE_NAME_NAME"] = "Customer middle name";
$MESS["SALE_ASSIST_PAYMENT_NAME"] = "Payment method";

$MESS["SALE_ASSIST_PAYMENT_CardPayment_NAME"] = "Use Assist authorization pages to authorize";
$MESS["SALE_ASSIST_PAYMENT_WalletPayment_NAME"] = "Use SET-authorization";
$MESS["SALE_ASSIST_PAYMENT_WebMoneyPayment_NAME"] = "Use WebMoney Transfer payment system";
$MESS["SALE_ASSIST_PAYMENT_EPortPayment_NAME"] = "Use E-Port payment system";
$MESS["SALE_ASSIST_PAYMENT_KreditPilotPayment_NAME"] = "Use KreditPilot payment system";
$MESS["SALE_ASSIST_PAYMENT_PayCashPayment_NAME"] = "Use PayCash payment system";
$MESS["SALE_ASSIST_PAYMENT_D_NAME"] = "1 - use, 0 - do not use";
$MESS["SALE_ASSIST_PAYMENT_EPBeelinePayment_NAME"] = "Use Beeline payment system";
$MESS["SALE_ASSIST_PAYMENT_EPBeelinePayment_DESC"] = "1 - use, 0 - do not use";
?>
