CREATE TABLE B_SALE_HDALE
(
	CODE VARCHAR(100 CHAR) NOT NULL,
	ID NUMBER(18) NOT NULL,
	NAME VARCHAR(100 CHAR) NOT NULL,
	PCITY VARCHAR(100 CHAR) NULL,
	PSUBREGION VARCHAR(100 CHAR) NULL,
	PREGION VARCHAR(100 CHAR) NULL,
	PCOUNTRY VARCHAR(100 CHAR) NULL,
	LOCATION_ID NUMBER(18) NULL,
	LOCATION_EXT_ID NUMBER(18) NULL
	PRIMARY KEY (CODE)
)
/
CREATE INDEX IX_BSHDALE_LOCATION_ID ON B_SALE_HDALE (LOCATION_ID)
/