export type User = {
	id: number,
	name: string,
	firstName: string,
	lastName: string,
	avatar: string,
	color: string,
	workPosition: string,
	gender: 'M' | 'F',
	extranet: boolean,
	network: boolean,
	bot: boolean,
	connector: boolean,
	externalAuthId: string,
	status: string,
	idle: boolean,
	lastActivityDate: false | Date,
	mobileLastDate: false | Date,
	isOnline: boolean,
	isMobileOnline: boolean,
	birthday: string,
	isBirthday: boolean,
	absent: string,
	isAbsent: boolean,
	departments: Array,
	phones: {
		workPhone: string,
		personalMobile: string,
		personalPhone: string,
		innerPhone: string,
	}
};