create table if not exists b_sale_hdale(
	CODE varchar(100) NOT NULL,
	ID INT NOT NULL,
	NAME varchar(100) NOT NULL,
	PCITY varchar(100) NULL,
	PSUBREGION varchar(100) NULL,
	PREGION varchar(100) NULL,
	PCOUNTRY varchar(100) NULL,
	LOCATION_ID INT NULL,
	LOCATION_EXT_ID INT NULL,
	PRIMARY KEY (CODE),
	INDEX IX_BSHDALE_LOCATION_ID(LOCATION_ID)
);

create table if not exists b_sale_ruspost_reliability(
	HASH CHAR(32) NOT NULL,
	RELIABILITY INT NULL,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	ADDRESS text NULL,
	FULL_NAME VARCHAR(255) NULL,
	PHONE VARCHAR(30) NULL,
	PRIMARY KEY (HASH)
);