<?php

use Bitrix\Main\Localization\Loc;

$sale_default_option = [
	'default_currency' => 'RUB',
	'product_reserve_clear_period' => 0,
	'product_reserve_condition' => 'O',
	'use_sale_discount_only' => 'N',
	'get_discount_percent_from_base_price' => 'N',
	'SALE_ADMIN_NEW_PRODUCT' => 'N',
	'discount_apply_mode' => 0x0000,
	'viewed_capability' => 'N',
	'encode_fuser_id' => 'N',
	'allow_deduction_on_delivery' => 'N',
	'status_on_payed_2_allow_delivery' => 'N',
	'show_basket_props_in_order_list' => 'Y',
	'basket_discount_converted' => 'N',
	'1C_IMPORT_UPDATE_BASKET_QUANTITY' => 'Y',
	'1C_IMPORT_NEW_PAYMENT' => 'Y',
	'1C_IMPORT_NEW_SHIPMENT' => 'Y',
	'1C_IMPORT_NEW_ORDER_NEW_SHIPMENT' => 'Y',
	'value_precision' => 2,
	'product_viewed_save' => 'N',
	'weight_unit' => Loc::getMessage('SMOD_PAR_WEIGHT_UNIT'),
	'weight_koef' => 1,
	'format_quantity' => 'AUTO',
	'affiliate_plan_type' => 'N',
	'expiration_processing_events' => '',
	'order_history_log_level' => '0',
	'order_history_action_log_level' => '0',
	'sale_ps_success_path' => '',
	'sale_ps_fail_path' => '',
	'allow_pay_status' => 'N',
	'check_type_on_pay' => 'sell',
	'basket_refresh_gap' => 0,
	'allow_guest_order_view' => 'N',
	'allow_guest_order_view_status' => '',
	'allow_guest_order_view_paths' => '',
	'sale_location_selector_appearance' => 'steps',
	'p2p_allow_collect_data' => 'N',
	'p2p_status_list' => '',
	'p2p_del_period' => 10,
	'p2p_del_exp' => 10,
	'p2p_limit_collecting_per_hit' => 100,
	'order_changes_cleaner_active' => 'N',
	'order_changes_cleaner_days' => 365,
	'order_changes_cleaner_limit' => 10000,
	'pay_amount' => serialize([
		[
			'AMOUNT' => 10,
			'CURRENCY' => 'EUR',
		],
		[
			'AMOUNT' => 20,
			'CURRENCY' => 'EUR',
		],
		[
			'AMOUNT' => 30,
			'CURRENCY' => 'EUR',
		],
		[
			'AMOUNT' => 40,
			'CURRENCY' => 'EUR',
		],
	]),
	'pay_reminder' => '',
	'subscribe_prod' => '',
	'WEIGHT_different_set' => 'N',
	'ADDRESS_different_set' => 'N',
	'use_ccards' => 'N',
	'sale_data_file' => '',
	'crypt_algorithm' => 'RC4',
	'status_on_paid' => '',
	'status_on_half_paid' => '',
	'status_on_change_allow_delivery_after_paid' => '',
	'status_on_allow_delivery' => '',
	'status_on_allow_delivery_one_of' => '',
	'status_on_shipped_shipment' => '',
	'status_on_shipped_shipment_one_of' => '',
	'shipment_status_on_allow_delivery' => '',
	'shipment_status_on_shipped' => '',
	'tracking_map_statuses' => '',
	'tracking_check_switch' => 'N',
	'tracking_check_period' => 24,
	'order_email' => '',
	'delete_after' => 30,
	'order_list_date' => 30,
	'MAX_LOCK_TIME' => 60,
	'GRAPH_WEIGHT' => 800,
	'GRAPH_HEIGHT' => 600,
	'path2user_ps_files' => BX_PERSONAL_ROOT . '/php_interface/include/sale_payment/',
	'lock_catalog' => 'Y',
	'affiliate_param_name' => 'partner',
	'affiliate_life_time' => 30,
	'show_order_sum' => 'N',
	'show_order_product_xml_id' => 'N',
	'show_paysystem_action_id' => 'N',
	'measurement_path' => '/bitrix/modules/sale/measurements.php',
	'delivery_handles_custom_path' => BX_PERSONAL_ROOT . '/php_interface/include/sale_delivery/',
	'use_secure_cookies' => 'N',
	'save_anonymous_fuser_cookie' => 'N',
	'COUNT_DISCOUNT_4_ALL_QUANTITY' => 'N',
	'COUNT_DELIVERY_TAX' => 'N',
	'QUANTITY_FACTORIAL' => 'N',
	'viewed_time' => 90,
	'viewed_count' => 100,
	'regular_archive_active' => 'N',
	'archive_time_limit' => '5',
	'sale_locationpro_migrated' => 'Y',
	'sale_locationpro_enabled' => 'Y',
];
