<?
if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED!==true)
{
	die();
}

use \Bitrix\Main\Localization\Loc;

Loc::loadMessages(
	\Bitrix\Landing\Manager::getDocRoot() .
	'/bitrix/modules/landing/blocks/.style.php'
);

return array(
	'style' => array(
		'text-align' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_TEXT_ALIGN'),
			'property' => 'text-align',
			'type' => 'buttons',
			'items' => array(
				array('name' => '<span class="landing-ui-align landing-ui-align-left"><em></em></span>', 'value' => 'text-left'),
				array('name' => '<span class="landing-ui-align landing-ui-align-center"><em></em></span>', 'value' => 'text-center'),
				array('name' => '<span class="landing-ui-align landing-ui-align-right"><em></em></span>', 'value' => 'text-right')
			)
		),
		'row-align' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_ROW_ALIGN'),
			'type' => 'buttons',
			'items' => array(
				array('name' => '<span class="landing-ui-align landing-ui-align-left"><em></em></span>', 'value' => 'justify-content-start'),
				array('name' => '<span class="landing-ui-align landing-ui-align-center"><em></em></span>', 'value' => 'justify-content-center'),
				array('name' => '<span class="landing-ui-align landing-ui-align-right"><em></em></span>', 'value' => 'justify-content-end')
			)
		),
		'color' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_TEXT_COLOR'),
			'property' => 'color',
			'type' => 'palette',
			'items' => array(
				array('name' => 'g-color-primary', 'value' => 'g-color-primary'),
				array('name' => 'g-color-primary-opacity-0_3', 'value' => 'g-color-primary-opacity-0_3'),
				array('name' => 'g-color-primary-opacity-0_4', 'value' => 'g-color-primary-opacity-0_4'),
				array('name' => 'g-color-black', 'value' => 'g-color-black'),
				array('name' => 'g-color-black-opacity-0_1', 'value' => 'g-color-black-opacity-0_1'),
				array('name' => 'g-color-black-opacity-0_3', 'value' => 'g-color-black-opacity-0_3'),
				array('name' => 'g-color-black-opacity-0_5', 'value' => 'g-color-black-opacity-0_5'),
				array('name' => 'g-color-black-opacity-0_6', 'value' => 'g-color-black-opacity-0_6'),
				array('name' => 'g-color-black-opacity-0_7', 'value' => 'g-color-black-opacity-0_7'),
				array('name' => 'g-color-black-opacity-0_8', 'value' => 'g-color-black-opacity-0_8'),
				array('name' => 'g-color-black-opacity-0_9', 'value' => 'g-color-black-opacity-0_9'),
				array('name' => 'g-color-white', 'value' => 'g-color-white'),
				array('name' => 'g-color-white-opacity-0_1', 'value' => 'g-color-white-opacity-0_1'),
				array('name' => 'g-color-white-opacity-0_2', 'value' => 'g-color-white-opacity-0_2'),
				array('name' => 'g-color-white-opacity-0_3', 'value' => 'g-color-white-opacity-0_3'),
				array('name' => 'g-color-white-opacity-0_5', 'value' => 'g-color-white-opacity-0_5'),
				array('name' => 'g-color-white-opacity-0_6', 'value' => 'g-color-white-opacity-0_6'),
				array('name' => 'g-color-white-opacity-0_7', 'value' => 'g-color-white-opacity-0_7'),
				array('name' => 'g-color-white-opacity-0_8', 'value' => 'g-color-white-opacity-0_8'),
				array('name' => 'g-color-white-opacity-0_9', 'value' => 'g-color-white-opacity-0_9'),
				array('name' => 'g-color-gray-light-v1', 'value' => 'g-color-gray-light-v1'),
				array('name' => 'g-color-gray-light-v2', 'value' => 'g-color-gray-light-v2'),
				array('name' => 'g-color-gray-light-v3', 'value' => 'g-color-gray-light-v3'),
				array('name' => 'g-color-gray-light-v4', 'value' => 'g-color-gray-light-v4'),
				array('name' => 'g-color-gray-light-v5', 'value' => 'g-color-gray-light-v5'),
				array('name' => 'g-color-gray-dark-v1', 'value' => 'g-color-gray-dark-v1'),
				array('name' => 'g-color-gray-dark-v2', 'value' => 'g-color-gray-dark-v2'),
				array('name' => 'g-color-gray-dark-v3', 'value' => 'g-color-gray-dark-v3'),
				array('name' => 'g-color-gray-dark-v4', 'value' => 'g-color-gray-dark-v4'),
				array('name' => 'g-color-gray-dark-v5', 'value' => 'g-color-gray-dark-v5'),
				array('name' => 'g-color-green', 'value' => 'g-color-green'),
				array('name' => 'g-color-blue', 'value' => 'g-color-blue'),
				array('name' => 'g-color-blue-dark-v1', 'value' => 'g-color-blue-dark-v1'),
				array('name' => 'g-color-lightblue', 'value' => 'g-color-lightblue'),
				array('name' => 'g-color-lightblue-v1', 'value' => 'g-color-lightblue-v1'),
				array('name' => 'g-color-darkblue', 'value' => 'g-color-darkblue'),
				array('name' => 'g-color-indigo', 'value' => 'g-color-indigo'),
				array('name' => 'g-color-red', 'value' => 'g-color-red'),
				array('name' => 'g-color-lightred', 'value' => 'g-color-lightred'),
				array('name' => 'g-color-darkred', 'value' => 'g-color-darkred'),
				array('name' => 'g-color-purple', 'value' => 'g-color-purple'),
				array('name' => 'g-color-darkpurple', 'value' => 'g-color-darkpurple'),
				array('name' => 'g-color-pink', 'value' => 'g-color-pink'),
				array('name' => 'g-color-pink-dark-v1', 'value' => 'g-color-pink-dark-v1'),
				array('name' => 'g-color-deeporange', 'value' => 'g-color-deeporange'),
				array('name' => 'g-color-yellow', 'value' => 'g-color-yellow'),
				array('name' => 'g-color-aqua', 'value' => 'g-color-aqua'),
				array('name' => 'g-color-aqua-dark-v1', 'value' => 'g-color-aqua-dark-v1'),
				array('name' => 'g-color-cyan', 'value' => 'g-color-cyan'),
				array('name' => 'g-color-teal', 'value' => 'g-color-teal'),
				array('name' => 'g-color-brown', 'value' => 'g-color-brown'),
				array('name' => 'g-color-bluegray', 'value' => 'g-color-bluegray'),
				
				array('name' => 'g-theme-event-color-gray-dark-v1', 'value' => 'g-theme-event-color-gray-dark-v1'),
			)
		),
		'background-color' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BACKGROUND_COLOR'),
			'property' => 'background-color',
			'type' => 'palette',
			'exclude' => 'background-gradient',
			'items' => array(
				array('name' => 'g-bg-primary', 'value' => 'g-bg-primary'),
				array('name' => 'g-bg-primary-dark-v1', 'value' => 'g-bg-primary-dark-v1'),
				array('name' => 'g-bg-primary-dark-v2', 'value' => 'g-bg-primary-dark-v2'),
				array('name' => 'g-bg-primary-dark-v3', 'value' => 'g-bg-primary-dark-v3'),
				array('name' => 'g-bg-primary-opacity-0_1', 'value' => 'g-bg-primary-opacity-0_1'),
				array('name' => 'g-bg-primary-opacity-0_2', 'value' => 'g-bg-primary-opacity-0_2'),
				array('name' => 'g-bg-primary-opacity-0_3', 'value' => 'g-bg-primary-opacity-0_3'),
				array('name' => 'g-bg-primary-opacity-0_4', 'value' => 'g-bg-primary-opacity-0_4'),
				array('name' => 'g-bg-primary-opacity-0_6', 'value' => 'g-bg-primary-opacity-0_6'),
				array('name' => 'g-bg-primary-opacity-0_8', 'value' => 'g-bg-primary-opacity-0_8'),
				array('name' => 'g-bg-primary-opacity-0_9', 'value' => 'g-bg-primary-opacity-0_9'),
				array('name' => 'g-bg-black', 'value' => 'g-bg-black'),
				array('name' => 'g-bg-main', 'value' => 'g-bg-main'),
				array('name' => 'g-bg-secondary', 'value' => 'g-bg-secondary'),
				array('name' => 'g-bg-black-opacity-0_1', 'value' => 'g-bg-black-opacity-0_1'),
				array('name' => 'g-bg-black-opacity-0_2', 'value' => 'g-bg-black-opacity-0_2'),
				array('name' => 'g-bg-black-opacity-0_3', 'value' => 'g-bg-black-opacity-0_3'),
				array('name' => 'g-bg-black-opacity-0_4', 'value' => 'g-bg-black-opacity-0_4'),
				array('name' => 'g-bg-black-opacity-0_5', 'value' => 'g-bg-black-opacity-0_5'),
				array('name' => 'g-bg-black-opacity-0_6', 'value' => 'g-bg-black-opacity-0_6'),
				array('name' => 'g-bg-black-opacity-0_7', 'value' => 'g-bg-black-opacity-0_7'),
				array('name' => 'g-bg-black-opacity-0_8', 'value' => 'g-bg-black-opacity-0_8'),
				array('name' => 'g-bg-black-opacity-0_9', 'value' => 'g-bg-black-opacity-0_9'),
				array('name' => 'g-bg-white', 'value' => 'g-bg-white'),
				array('name' => 'g-bg-white-opacity-0_1', 'value' => 'g-bg-white-opacity-0_1'),
				array('name' => 'g-bg-white-opacity-0_3', 'value' => 'g-bg-white-opacity-0_3'),
				array('name' => 'g-bg-white-opacity-0_5', 'value' => 'g-bg-white-opacity-0_5'),
				array('name' => 'g-bg-white-opacity-0_7', 'value' => 'g-bg-white-opacity-0_7'),
				array('name' => 'g-bg-white-opacity-0_8', 'value' => 'g-bg-white-opacity-0_8'),
				array('name' => 'g-bg-white-opacity-0_9', 'value' => 'g-bg-white-opacity-0_9'),
				array('name' => 'g-bg-gray-dark-v1', 'value' => 'g-bg-gray-dark-v1'),
				array('name' => 'g-theme-photography-bg-gray-dark-v2', 'value' => 'g-theme-photography-bg-gray-dark-v2'),
				array('name' => 'g-theme-photography-bg-gray-dark-v3', 'value' => 'g-theme-photography-bg-gray-dark-v3'),
				array('name' => 'g-theme-photography-bg-gray-dark-v4', 'value' => 'g-theme-photography-bg-gray-dark-v4'),
				array('name' => 'g-bg-gray-dark-v2', 'value' => 'g-bg-gray-dark-v2'),
				array('name' => 'g-bg-gray-dark-v3', 'value' => 'g-bg-gray-dark-v3'),
				array('name' => 'g-bg-gray-dark-v4', 'value' => 'g-bg-gray-dark-v4'),
				array('name' => 'g-bg-gray-dark-v5', 'value' => 'g-bg-gray-dark-v5'),
				array('name' => 'g-bg-gray-light-v1', 'value' => 'g-bg-gray-light-v1'),
				array('name' => 'g-bg-gray-light-v2', 'value' => 'g-bg-gray-light-v2'),
				array('name' => 'g-bg-gray-light-v3', 'value' => 'g-bg-gray-light-v3'),
				array('name' => 'g-bg-gray-light-v4', 'value' => 'g-bg-gray-light-v4'),
				array('name' => 'g-bg-gray-light-v5', 'value' => 'g-bg-gray-light-v5'),
				array('name' => 'g-bg-beige', 'value' => 'g-bg-beige'),
				array('name' => 'g-bg-green', 'value' => 'g-bg-green'),
				array('name' => 'g-bg-green-opacity-0_1', 'value' => 'g-bg-green-opacity-0_1'),
				array('name' => 'g-bg-blue', 'value' => 'g-bg-blue'),
				array('name' => 'g-bg-blue-opacity-0_1', 'value' => 'g-bg-blue-opacity-0_1'),
				array('name' => 'g-bg-blue-opacity-0_7', 'value' => 'g-bg-blue-opacity-0_7'),
				array('name' => 'g-bg-blue-opacity-0_9', 'value' => 'g-bg-blue-opacity-0_9'),
				array('name' => 'g-bg-lightblue', 'value' => 'g-bg-lightblue'),
				array('name' => 'g-bg-lightblue-opacity-0_1', 'value' => 'g-bg-lightblue-opacity-0_1'),
				array('name' => 'g-bg-lightblue-v1', 'value' => 'g-bg-lightblue-v1'),
				array('name' => 'g-bg-lightblue-v1-opacity-0_1', 'value' => 'g-bg-lightblue-v1-opacity-0_1'),
				array('name' => 'g-bg-darkblue', 'value' => 'g-bg-darkblue'),
				array('name' => 'g-bg-darkblue-opacity-0_1', 'value' => 'g-bg-darkblue-opacity-0_1'),
				array('name' => 'g-bg-indigo', 'value' => 'g-bg-indigo'),
				array('name' => 'g-bg-indigo-opacity-0_1', 'value' => 'g-bg-indigo-opacity-0_1'),
				array('name' => 'g-bg-red', 'value' => 'g-bg-red'),
				array('name' => 'g-bg-red-opacity-0_1', 'value' => 'g-bg-red-opacity-0_1'),
				array('name' => 'g-bg-red-opacity-0_2', 'value' => 'g-bg-red-opacity-0_2'),
				array('name' => 'g-bg-red-opacity-0_5', 'value' => 'g-bg-red-opacity-0_5'),
				array('name' => 'g-bg-red-opacity-0_8', 'value' => 'g-bg-red-opacity-0_8'),
				array('name' => 'g-bg-lightred', 'value' => 'g-bg-lightred'),
				array('name' => 'g-bg-lightred-opacity-0_1', 'value' => 'g-bg-lightred-opacity-0_1'),
				array('name' => 'g-bg-darkred', 'value' => 'g-bg-darkred'),
				array('name' => 'g-bg-darkred-opacity-0_1', 'value' => 'g-bg-darkred-opacity-0_1'),
				array('name' => 'g-bg-purple', 'value' => 'g-bg-purple'),
				array('name' => 'g-bg-purple-opacity-0_1', 'value' => 'g-bg-purple-opacity-0_1'),
				array('name' => 'g-bg-purple-opacity-0_7', 'value' => 'g-bg-purple-opacity-0_7'),
				array('name' => 'g-bg-purple-opacity-0_9', 'value' => 'g-bg-purple-opacity-0_9'),
				array('name' => 'g-bg-darkpurple', 'value' => 'g-bg-darkpurple'),
				array('name' => 'g-bg-darkpurple-opacity-0_1', 'value' => 'g-bg-darkpurple-opacity-0_1'),
				array('name' => 'g-bg-pink', 'value' => 'g-bg-pink'),
				array('name' => 'g-bg-pink-opacity-0_1', 'value' => 'g-bg-pink-opacity-0_1'),
				array('name' => 'g-bg-pink-opacity-0_9', 'value' => 'g-bg-pink-opacity-0_9'),
				array('name' => 'g-bg-orange', 'value' => 'g-bg-orange'),
				array('name' => 'g-bg-orange-opacity-0_1', 'value' => 'g-bg-orange-opacity-0_1'),
				array('name' => 'g-bg-orange-opacity-0_2', 'value' => 'g-bg-orange-opacity-0_2'),
				array('name' => 'g-bg-deeporange', 'value' => 'g-bg-deeporange'),
				array('name' => 'g-bg-deeporange-opacity-0_1', 'value' => 'g-bg-deeporange-opacity-0_1'),
				array('name' => 'g-bg-yellow', 'value' => 'g-bg-yellow'),
				array('name' => 'g-bg-yellow-opacity-0_1', 'value' => 'g-bg-yellow-opacity-0_1'),
				array('name' => 'g-bg-yellow-opacity-0_7', 'value' => 'g-bg-yellow-opacity-0_7'),
				array('name' => 'g-bg-aqua', 'value' => 'g-bg-aqua'),
				array('name' => 'g-bg-aqua-opacity-0_1', 'value' => 'g-bg-aqua-opacity-0_1'),
				array('name' => 'g-bg-aqua-opacity-0_9', 'value' => 'g-bg-aqua-opacity-0_9'),
				array('name' => 'g-bg-cyan', 'value' => 'g-bg-cyan'),
				array('name' => 'g-bg-cyan-opacity-0_1', 'value' => 'g-bg-cyan-opacity-0_1'),
				array('name' => 'g-bg-cyan-opacity-0_9', 'value' => 'g-bg-cyan-opacity-0_9'),
				array('name' => 'g-bg-teal', 'value' => 'g-bg-teal'),
				array('name' => 'g-bg-teal-opacity-0_1', 'value' => 'g-bg-teal-opacity-0_1'),
				array('name' => 'g-bg-teal-opacity-0_9', 'value' => 'g-bg-teal-opacity-0_9'),
				array('name' => 'g-bg-brown', 'value' => 'g-bg-brown'),
				array('name' => 'g-bg-brown-opacity-0_1', 'value' => 'g-bg-brown-opacity-0_1'),
				array('name' => 'g-bg-bluegray', 'value' => 'g-bg-bluegray'),
				array('name' => 'g-bg-bluegray-opacity-0_3', 'value' => 'g-bg-bluegray-opacity-0_3'),
				array('name' => 'g-bg-bluegray-opacity-0_5', 'value' => 'g-bg-bluegray-opacity-0_5'),
				array('name' => 'g-bg-bluegray-opacity-0_7', 'value' => 'g-bg-bluegray-opacity-0_7'),
				
				array('name' => 'g-theme-business-bg-blue-dark-v1', 'value' => 'g-theme-business-bg-blue-dark-v1'),
				array('name' => 'g-theme-business-bg-blue-dark-v1-opacity-0_9', 'value' => 'g-theme-business-bg-blue-dark-v1-opacity-0_9'),
				array('name' => 'g-theme-business-bg-blue-dark-v2', 'value' => 'g-theme-business-bg-blue-dark-v2'),
				array('name' => 'g-theme-business-bg-blue-dark-v3', 'value' => 'g-theme-business-bg-blue-dark-v3'),
				array('name' => 'g-theme-architecture-bg-blue-dark-v1', 'value' => 'g-theme-architecture-bg-blue-dark-v1'),
				array('name' => 'g-theme-architecture-bg-blue-dark-v3', 'value' => 'g-theme-architecture-bg-blue-dark-v3'),
				array('name' => 'g-theme-architecture-bg-blue-dark-v4', 'value' => 'g-theme-architecture-bg-blue-dark-v4'),
//				array('name' => 'g-theme-architecture-bg-blue-dark-v2', 'value' => 'g-theme-architecture-bg-blue-dark-v2'),
//				array('name' => 'g-theme-event-bg-blue-dark-v2', 'value' => 'g-theme-event-bg-blue-dark-v2'),
				array('name' => 'g-theme-lawyer-bg-gray-dark-v1', 'value' => 'g-theme-lawyer-bg-gray-dark-v1'),
				array('name' => 'g-theme-event-bg-blue-dark-v2', 'value' => 'g-theme-event-bg-blue-dark-v2'),
				array('name' => 'g-theme-travel-bg-black-v1', 'value' => 'g-theme-travel-bg-black-v1'),
			)
		),
		'background-gradient' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BACKGROUND_GRADIENT'),
			'property' => 'background-image',
			'type' => 'palette',
			'exclude' => 'background-color',
			'items' => array(
				array('name' => 'g-bg-gray-lineargradient', 'value' => 'g-bg-gray-lineargradient'),
				array('name' => 'g-bg-bluepink-lineargradien', 'value' => 'g-bg-bluepink-lineargradien'),
				array('name' => 'g-bg-blue-lineargradient', 'value' => 'g-bg-blue-lineargradient'),
				array('name' => 'g-bg-blue-lineargradient-v2', 'value' => 'g-bg-blue-lineargradient-v2'),
				array('name' => 'g-bg-blue-lineargradient-v3', 'value' => 'g-bg-blue-lineargradient-v3'),
				array('name' => 'g-bg-blue-lineargradient-v4', 'value' => 'g-bg-blue-lineargradient-v4'),
				array('name' => 'g-bg-blue-lineargradient-v5', 'value' => 'g-bg-blue-lineargradient-v5'),
				array('name' => 'g-bg-orange-lineargradient', 'value' => 'g-bg-orange-lineargradient'),
				array('name' => 'g-bg-orange-lineargradient-v2', 'value' => 'g-bg-orange-lineargradient-v2'),
				array('name' => 'g-bg-yellow-lineargradient', 'value' => 'g-bg-yellow-lineargradient'),
				array('name' => 'g-bg-darkpurple-lineargradient', 'value' => 'g-bg-darkpurple-lineargradient'),
				array('name' => 'g-bg-bluegray-lineargradient', 'value' => 'g-bg-bluegray-lineargradient'),
				array('name' => 'g-bg-pink-lineargradient', 'value' => 'g-bg-pink-lineargradient'),
				array('name' => 'g-bg-pink-lineargradient-v2', 'value' => 'g-bg-pink-lineargradient-v2'),
				array('name' => 'g-bg-red-lineargradient', 'value' => 'g-bg-red-lineargradient'),
				array('name' => 'g-bg-black-gradient-opacity-v1', 'value' => 'g-bg-black-gradient-opacity-v1'),
				array('name' => 'g-bg-green-gradient-opacity-v1', 'value' => 'g-bg-green-gradient-opacity-v1'),
				array('name' => 'g-bg-purple-gradient-opacity-v1', 'value' => 'g-bg-purple-gradient-opacity-v1'),
				array('name' => 'g-bg-pink-gradient-opacity-v1', 'value' => 'g-bg-pink-gradient-opacity-v1'),
				array('name' => 'g-bg-cyan-gradient-opacity-v1', 'value' => 'g-bg-cyan-gradient-opacity-v1'),
				array('name' => 'g-bg-lightblue-radialgradient-ellipse', 'value' => 'g-bg-lightblue-radialgradient-ellipse'),
				array('name' => 'g-bg-gray-radialgradient-ellipse', 'value' => 'g-bg-gray-radialgradient-ellipse'),
				array('name' => 'g-bg-graylight-radialgradient-ellipse', 'value' => 'g-bg-graylight-radialgradient-ellipse'),
				array('name' => 'g-bg-lightblue-radialgradient-circle', 'value' => 'g-bg-lightblue-radialgradient-circle'),
				array('name' => 'g-bg-blue-radialgradient-circle', 'value' => 'g-bg-blue-radialgradient-circle'),
				array('name' => 'g-bg-darkgray-radialgradient-circle', 'value' => 'g-bg-darkgray-radialgradient-circle'),
				array('name' => 'g-bg-blue-radialgradient-circle-endless', 'value' => 'g-bg-blue-radialgradient-circle-endless'),
				array('name' => 'g-bg-gray-verticalstripes-endless', 'value' => 'g-bg-gray-verticalstripes-endless'),
				array('name' => 'g-bg-pattern-gray-v1', 'value' => 'g-bg-pattern-gray-v1'),
				array('name' => 'g-bg-pattern-green-v1', 'value' => 'g-bg-pattern-green-v1'),
				array('name' => 'g-bg-pattern-dark-v1', 'value' => 'g-bg-pattern-dark-v1'),
			)
		),
		'border-color' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BORDER_COLOR'),
			'property' => 'border-color',
			'type' => 'palette',
			'items' => array(
				array('name' => 'g-brd-primary', 'value' => 'g-brd-primary'),
				array('name' => 'g-brd-primary-opacity-0_3', 'value' => 'g-brd-primary-opacity-0_3'),
				array('name' => 'g-brd-primary-dark-dark-v1', 'value' => 'g-brd-primary-dark-dark-v1'),
				array('name' => 'g-brd-primary-dark-dark-v2', 'value' => 'g-brd-primary-dark-dark-v2'),
				array('name' => 'g-brd-primary-dark-dark-v3', 'value' => 'g-brd-primary-dark-dark-v3'),
				array('name' => 'g-brd-main', 'value' => 'g-brd-main'),
				array('name' => 'g-brd-black', 'value' => 'g-brd-black'),
				array('name' => 'g-brd-black-opacity-0_4', 'value' => 'g-brd-black-opacity-0_4'),
				array('name' => 'g-brd-white', 'value' => 'g-brd-white'),
				array('name' => 'g-brd-white-opacity-0_1', 'value' => 'g-brd-white-opacity-0_1'),
				array('name' => 'g-brd-white-opacity-0_2', 'value' => 'g-brd-white-opacity-0_2'),
				array('name' => 'g-brd-white-opacity-0_3', 'value' => 'g-brd-white-opacity-0_3'),
				array('name' => 'g-brd-white-opacity-0_4', 'value' => 'g-brd-white-opacity-0_4'),
				array('name' => 'g-brd-white-opacity-0_5', 'value' => 'g-brd-white-opacity-0_5'),
				array('name' => 'g-brd-white-opacity-0_6', 'value' => 'g-brd-white-opacity-0_6'),
				array('name' => 'g-brd-white-opacity-0_8', 'value' => 'g-brd-white-opacity-0_8'),
				array('name' => 'g-brd-gray-dark-v1', 'value' => 'g-brd-gray-dark-v1'),
				array('name' => 'g-brd-gray-dark-v2', 'value' => 'g-brd-gray-dark-v2'),
				array('name' => 'g-brd-gray-dark-v3', 'value' => 'g-brd-gray-dark-v3'),
				array('name' => 'g-brd-gray-dark-v4', 'value' => 'g-brd-gray-dark-v4'),
				array('name' => 'g-brd-gray-dark-v5', 'value' => 'g-brd-gray-dark-v5'),
				array('name' => 'g-brd-gray-light-v1', 'value' => 'g-brd-gray-light-v1'),
				array('name' => 'g-brd-gray-light-v2', 'value' => 'g-brd-gray-light-v2'),
				array('name' => 'g-brd-gray-light-v3', 'value' => 'g-brd-gray-light-v3'),
				array('name' => 'g-brd-gray-light-v4', 'value' => 'g-brd-gray-light-v4'),
				array('name' => 'g-brd-gray-light-v5', 'value' => 'g-brd-gray-light-v5'),
				array('name' => 'g-brd-transparent', 'value' => 'g-brd-transparent'),
				array('name' => 'g-brd-green', 'value' => 'g-brd-green'),
				array('name' => 'g-brd-blue', 'value' => 'g-brd-blue'),
				array('name' => 'g-brd-lightblue', 'value' => 'g-brd-lightblue'),
				array('name' => 'g-brd-darkblue', 'value' => 'g-brd-darkblue'),
				array('name' => 'g-brd-indigo', 'value' => 'g-brd-indigo'),
				array('name' => 'g-brd-purple', 'value' => 'g-brd-purple'),
				array('name' => 'g-brd-darkpurple', 'value' => 'g-brd-darkpurple'),
				array('name' => 'g-brd-pink', 'value' => 'g-brd-pink'),
				array('name' => 'g-brd-red', 'value' => 'g-brd-red'),
				array('name' => 'g-brd-lightred', 'value' => 'g-brd-lightred'),
				array('name' => 'g-brd-darkred', 'value' => 'g-brd-darkred'),
				array('name' => 'g-brd-orange', 'value' => 'g-brd-orange'),
				array('name' => 'g-brd-deeporange', 'value' => 'g-brd-deeporange'),
				array('name' => 'g-brd-yellow', 'value' => 'g-brd-yellow'),
				array('name' => 'g-brd-aqua', 'value' => 'g-brd-aqua'),
				array('name' => 'g-brd-cyan', 'value' => 'g-brd-cyan'),
				array('name' => 'g-brd-teal', 'value' => 'g-brd-teal'),
				array('name' => 'g-brd-brown', 'value' => 'g-brd-brown'),
				array('name' => 'g-brd-bluegray', 'value' => 'g-brd-bluegray'),
				array('name' => 'g-brd-pinterest', 'value' => 'g-brd-pinterest'),
				array('name' => 'g-brd-cyan-gradient-opacity-v1', 'value' => 'g-brd-cyan-gradient-opacity-v1'),
			)
		),
		'font-size' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_FONT_SIZE'),
			'property' => 'font-size',
			'type' => 'slider',
			'items' => array(
				array('name' => Loc::getMessage('LANDING_STYLE_AUTO'), 'value' => 'g-font-size-0'),
				array('name' => '5', 'value' => 'g-font-size-5'),
				array('name' => '8', 'value' => 'g-font-size-8'),
				array('name' => '9', 'value' => 'g-font-size-9'),
				array('name' => '10', 'value' => 'g-font-size-10'),
				array('name' => '11', 'value' => 'g-font-size-11'),
				array('name' => '12', 'value' => 'g-font-size-12'),
				array('name' => '13', 'value' => 'g-font-size-13'),
				array('name' => '14', 'value' => 'g-font-size-14'),
				array('name' => '15', 'value' => 'g-font-size-15'),
				array('name' => '16', 'value' => 'g-font-size-16'),
				array('name' => '17', 'value' => 'g-font-size-17'),
				array('name' => '18', 'value' => 'g-font-size-18'),
				array('name' => '20', 'value' => 'g-font-size-20'),
				array('name' => '22', 'value' => 'g-font-size-22'),
				array('name' => '23', 'value' => 'g-font-size-23'),
				array('name' => '24', 'value' => 'g-font-size-24'),
				array('name' => '25', 'value' => 'g-font-size-25'),
				array('name' => '26', 'value' => 'g-font-size-26'),
				array('name' => '27', 'value' => 'g-font-size-27'),
				array('name' => '28', 'value' => 'g-font-size-28'),
				array('name' => '30', 'value' => 'g-font-size-30'),
				array('name' => '32', 'value' => 'g-font-size-32'),
				array('name' => '33', 'value' => 'g-font-size-33'),
				array('name' => '35', 'value' => 'g-font-size-35'),
				array('name' => '36', 'value' => 'g-font-size-36'),
				array('name' => '38', 'value' => 'g-font-size-38'),
				array('name' => '40', 'value' => 'g-font-size-40'),
				array('name' => '42', 'value' => 'g-font-size-42'),
				array('name' => '45', 'value' => 'g-font-size-45'),
				array('name' => '46', 'value' => 'g-font-size-46'),
				array('name' => '48', 'value' => 'g-font-size-48'),
				array('name' => '50', 'value' => 'g-font-size-50'),
				array('name' => '55', 'value' => 'g-font-size-55'),
				array('name' => '60', 'value' => 'g-font-size-60'),
				array('name' => '65', 'value' => 'g-font-size-65'),
				array('name' => '70', 'value' => 'g-font-size-70'),
				array('name' => '75', 'value' => 'g-font-size-75'),
				array('name' => '76', 'value' => 'g-font-size-76'),
				array('name' => '80', 'value' => 'g-font-size-80'),
				array('name' => '86', 'value' => 'g-font-size-86'),
				array('name' => '90', 'value' => 'g-font-size-90'),
				array('name' => '120', 'value' => 'g-font-size-120'),
				array('name' => '180', 'value' => 'g-font-size-180'),
				array('name' => '200', 'value' => 'g-font-size-200')
			)
		),
		'font-family' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_FONT_FAMILY'),
			'property' => 'font-family',
			'type' => 'list',
			'items' => array(
				array('name' => 'Open Sans', 'value' => 'g-font-open-sans'),
				array('name' => 'Helvetica', 'value' => 'g-font-helvetica'),
				array('name' => 'Montserrat', 'value' => 'g-font-montserrat'),
				array('name' => 'Roboto', 'value' => 'g-font-roboto'),
				array('name' => 'Roboto Slab', 'value' => 'g-font-roboto-slab'),
				array('name' => 'PT Sans', 'value' => 'g-font-pt-sans'),
				array('name' => 'PT Sans Narrow', 'value' => 'g-font-pt-sans-narrow'),
				array('name' => 'PT Sans Caption', 'value' => 'g-font-pt-sans-caption'),
				array('name' => 'Cormorant Infant', 'value' => 'g-font-cormorant-infant'),
				array('name' => 'Alegreya Sans', 'value' => 'g-font-alegreya-sans'),
				array('name' => 'Lobster', 'value' => 'g-font-lobster'),
				array('name' => 'Menlo', 'value' => 'g-font-code'),
			)
		),
		'text-transform' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_TEXT_TRANSFORM'),
			'property' => 'text-transform',
			'type' => 'list',
			'items' => array(
				array('name' => Loc::getMessage('LANDING_STYLE_DEFAULT'), 'value' => 'g-text-transform-none'),
				array('name' => Loc::getMessage('LANDING_STYLE_UPPERCASE'), 'value' => 'text-uppercase'),
				array('name' => Loc::getMessage('LANDING_STYLE_LOWERCASE'), 'value' => 'text-lowercase'),
				array('name' => Loc::getMessage('LANDING_STYLE_UNDERLINE'), 'value' => 'g-text-underline'),
				array('name' => Loc::getMessage('LANDING_STYLE_STRIKE'), 'value' => 'g-text-strike')
			)
		),
		'line-height' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_LINE_HEIGHT'),
			'property' => 'line-height',
			'type' => 'slider',
			'items' => array(
				array('name' => Loc::getMessage('LANDING_STYLE_AUTO'), 'value' => 'g-line-height-0'),
				array('name' => '0.7', 'value' => 'g-line-height-0_7'),
				array('name' => '0.8', 'value' => 'g-line-height-0_8'),
				array('name' => '0.9', 'value' => 'g-line-height-0_9'),
				array('name' => '1', 'value' => 'g-line-height-1'),
				array('name' => '1.1', 'value' => 'g-line-height-1_1'),
				array('name' => '1.2', 'value' => 'g-line-height-1_2'),
				array('name' => '1.3', 'value' => 'g-line-height-1_3'),
				array('name' => '1.4', 'value' => 'g-line-height-1_4'),
				array('name' => '1.5', 'value' => 'g-line-height-1_5'),
				array('name' => '1.6', 'value' => 'g-line-height-1_6'),
				array('name' => '1.8', 'value' => 'g-line-height-1_8'),
				array('name' => '2', 'value' => 'g-line-height-2')
			)
		),
		'letter-spacing' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_LETTER_SPACING'),
			'property' => 'letter-spacing',
			'type' => 'slider',
			'items' => array(
				array('name' => '-2', 'value' => 'g-letter-spacing-minus-2'),
				array('name' => '0', 'value' => 'g-letter-spacing-0'),
				array('name' => '0.5', 'value' => 'g-letter-spacing-0_5'),
				array('name' => '1', 'value' => 'g-letter-spacing-1'),
				array('name' => '1.5', 'value' => 'g-letter-spacing-1_5'),
				array('name' => '2', 'value' => 'g-letter-spacing-2'),
				array('name' => '3', 'value' => 'g-letter-spacing-3'),
				array('name' => '4', 'value' => 'g-letter-spacing-4'),
				array('name' => '5', 'value' => 'g-letter-spacing-5'),
				array('name' => '6', 'value' => 'g-letter-spacing-6'),
				array('name' => '7', 'value' => 'g-letter-spacing-7'),
				array('name' => '8', 'value' => 'g-letter-spacing-8'),
				array('name' => '9', 'value' => 'g-letter-spacing-9'),
				array('name' => '10', 'value' => 'g-letter-spacing-10'),
				array('name' => '11', 'value' => 'g-letter-spacing-11'),
				array('name' => '12', 'value' => 'g-letter-spacing-12')
			)
		),
		'box-shadow' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW'),
			'property' => 'box-shadow',
			'type' => 'list',
			'items' => array(
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_WITHOUT_SHADOW'), 'value' => 'g-box-shadow-none'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 1", 'value' => 'u-shadow-v1-1'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 2", 'value' => 'u-shadow-v1-2'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 3", 'value' => 'u-shadow-v1-3'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 4", 'value' => 'u-shadow-v1-4'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 5", 'value' => 'u-shadow-v1-5'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 6", 'value' => 'u-shadow-v1-6'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 7", 'value' => 'u-shadow-v1-7'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 8", 'value' => 'u-shadow-v6'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 9", 'value' => 'u-shadow-v7'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 10", 'value' => 'u-shadow-v8'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 11", 'value' => 'u-shadow-v9'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 12", 'value' => 'u-shadow-v10'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 13", 'value' => 'u-shadow-v11'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 14", 'value' => 'u-shadow-v12'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 15", 'value' => 'u-shadow-v13'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 16", 'value' => 'u-shadow-v14'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 17", 'value' => 'u-shadow-v15'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 18", 'value' => 'u-shadow-v16'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 19", 'value' => 'u-shadow-v17'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 20", 'value' => 'u-shadow-v18'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 21", 'value' => 'u-shadow-v19'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 22", 'value' => 'u-shadow-v20'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 23", 'value' => 'u-shadow-v21'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 24", 'value' => 'u-shadow-v22'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 25", 'value' => 'u-shadow-v23'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 26", 'value' => 'u-shadow-v24'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 27", 'value' => 'u-shadow-v25'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 28", 'value' => 'u-shadow-v26'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 29", 'value' => 'u-shadow-v27')
			)
		),
		'text-shadow' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_TEXT_SHADOW'),
			'property' => 'text-shadow',
			'type' => 'list',
			'items' => array(
				array('name' => Loc::getMessage('LANDING_TEXT_STYLE_WITHOUT_SHADOW'), 'value' => 'g-text-shadow-none'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 1", 'value' => 'custom-text-shadow-1'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 2", 'value' => 'custom-text-shadow-2'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 3", 'value' => 'custom-text-shadow-3'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 4", 'value' => 'custom-text-shadow-4'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 5", 'value' => 'custom-text-shadow-5'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 6", 'value' => 'custom-text-shadow-6'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 7", 'value' => 'custom-text-shadow-7'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 8", 'value' => 'custom-text-shadow-8'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 9", 'value' => 'custom-text-shadow-9'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 10", 'value' => 'custom-text-shadow-10'),
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_SHADOW_NAME')." 11", 'value' => 'custom-text-shadow-11')
			)
		),
		'opacity' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_OPACITY'),
			'property' => 'opacity',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'opacity-1'),
				array('name' => '20%', 'value' => 'g-opacity-0_8'),
				array('name' => '30%', 'value' => 'g-opacity-0_7'),
				array('name' => '40%', 'value' => 'g-opacity-0_6'),
				array('name' => '50%', 'value' => 'g-opacity-0_5'),
				array('name' => '60%', 'value' => 'g-opacity-0_4'),
				array('name' => '70%', 'value' => 'g-opacity-0_3'),
				array('name' => '100%', 'value' => 'opacity-0'),
			)
		),
		'padding-top' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_PADDING_TOP'),
			'property' => 'padding-top',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'g-pt-0'),
				array('name' => '2', 'value' => 'g-pt-2'),
				array('name' => '3', 'value' => 'g-pt-3'),
				array('name' => '5', 'value' => 'g-pt-5'),
				array('name' => '7', 'value' => 'g-pt-7'),
				array('name' => '10', 'value' => 'g-pt-10'),
				array('name' => '15', 'value' => 'g-pt-15'),
				array('name' => '20', 'value' => 'g-pt-20'),
				array('name' => '25', 'value' => 'g-pt-25'),
				array('name' => '30', 'value' => 'g-pt-30'),
				array('name' => '35', 'value' => 'g-pt-35'),
				array('name' => '40', 'value' => 'g-pt-40'),
				array('name' => '45', 'value' => 'g-pt-45'),
				array('name' => '50', 'value' => 'g-pt-50'),
				array('name' => '55', 'value' => 'g-pt-55'),
				array('name' => '60', 'value' => 'g-pt-60'),
				array('name' => '65', 'value' => 'g-pt-65'),
				array('name' => '70', 'value' => 'g-pt-70'),
				array('name' => '75', 'value' => 'g-pt-75'),
				array('name' => '80', 'value' => 'g-pt-80'),
				array('name' => '85', 'value' => 'g-pt-85'),
				array('name' => '90', 'value' => 'g-pt-90'),
				array('name' => '95', 'value' => 'g-pt-95'),
				array('name' => '100', 'value' => 'g-pt-100'),
				array('name' => '105', 'value' => 'g-pt-105'),
				array('name' => '110', 'value' => 'g-pt-110'),
				array('name' => '115', 'value' => 'g-pt-115'),
				array('name' => '120', 'value' => 'g-pt-120'),
				array('name' => '125', 'value' => 'g-pt-125'),
				array('name' => '130', 'value' => 'g-pt-130'),
				array('name' => '135', 'value' => 'g-pt-135'),
				array('name' => '140', 'value' => 'g-pt-140'),
				array('name' => '145', 'value' => 'g-pt-145'),
				array('name' => '150', 'value' => 'g-pt-150')
			)
		),
		'height-vh' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_HEIGHT_VH'),
			'property' => 'height',
			'type' => 'slider',
			'items' => array(
				array('name' => '33%', 'value' => 'g-height-33vh'),
				array('name' => '40%', 'value' => 'g-height-40vh'),
				array('name' => '50%', 'value' => 'g-height-50vh'),
				array('name' => '60%', 'value' => 'g-height-60vh'),
				array('name' => '70%', 'value' => 'g-height-70vh'),
				array('name' => '75%', 'value' => 'g-height-75vh'),
				array('name' => '80%', 'value' => 'g-height-80vh'),
				array('name' => '90%', 'value' => 'g-height-90vh'),
				array('name' => '95%', 'value' => 'g-height-95vh'),
				array('name' => '100%', 'value' => 'g-height-100vh'),
			)
		),
		'padding-bottom' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_PADDING_BOTTOM'),
			'property' => 'padding-bottom',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'g-pb-0'),
				array('name' => '2', 'value' => 'g-pb-2'),
				array('name' => '3', 'value' => 'g-pb-3'),
				array('name' => '4', 'value' => 'g-pb-5'),
				array('name' => '7', 'value' => 'g-pb-7'),
				array('name' => '10', 'value' => 'g-pb-10'),
				array('name' => '15', 'value' => 'g-pb-15'),
				array('name' => '20', 'value' => 'g-pb-20'),
				array('name' => '25', 'value' => 'g-pb-25'),
				array('name' => '30', 'value' => 'g-pb-30'),
				array('name' => '35', 'value' => 'g-pb-35'),
				array('name' => '40', 'value' => 'g-pb-40'),
				array('name' => '45', 'value' => 'g-pb-45'),
				array('name' => '50', 'value' => 'g-pb-50'),
				array('name' => '55', 'value' => 'g-pb-55'),
				array('name' => '60', 'value' => 'g-pb-60'),
				array('name' => '65', 'value' => 'g-pb-65'),
				array('name' => '70', 'value' => 'g-pb-70'),
				array('name' => '75', 'value' => 'g-pb-75'),
				array('name' => '80', 'value' => 'g-pb-80'),
				array('name' => '85', 'value' => 'g-pb-85'),
				array('name' => '90', 'value' => 'g-pb-90'),
				array('name' => '95', 'value' => 'g-pb-95'),
				array('name' => '100', 'value' => 'g-pb-100'),
				array('name' => '105', 'value' => 'g-pb-105'),
				array('name' => '110', 'value' => 'g-pb-110'),
				array('name' => '115', 'value' => 'g-pb-115'),
				array('name' => '120', 'value' => 'g-pb-120'),
				array('name' => '125', 'value' => 'g-pb-125'),
				array('name' => '130', 'value' => 'g-pb-130'),
				array('name' => '135', 'value' => 'g-pb-135'),
				array('name' => '140', 'value' => 'g-pb-140'),
				array('name' => '145', 'value' => 'g-pb-145'),
				array('name' => '150', 'value' => 'g-pb-150')
			)
		),
		'padding-left' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_PADDING_LEFT'),
			'property' => 'padding-left',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'g-pl-0'),
				array('name' => '1', 'value' => 'g-pl-1'),
				array('name' => '2', 'value' => 'g-pl-2'),
				array('name' => '3', 'value' => 'g-pl-3'),
				array('name' => '4', 'value' => 'g-pl-4'),
				array('name' => '5', 'value' => 'g-pl-5'),
				array('name' => '6', 'value' => 'g-pl-6'),
				array('name' => '7', 'value' => 'g-pl-7'),
				array('name' => '8', 'value' => 'g-pl-8'),
				array('name' => '9', 'value' => 'g-pl-9'),
				array('name' => '10', 'value' => 'g-pl-10'),
				array('name' => '15', 'value' => 'g-pl-15'),
				array('name' => '20', 'value' => 'g-pl-20'),
				array('name' => '25', 'value' => 'g-pl-25'),
				array('name' => '30', 'value' => 'g-pl-30'),
				array('name' => '35', 'value' => 'g-pl-35'),
				array('name' => '40', 'value' => 'g-pl-40'),
				array('name' => '45', 'value' => 'g-pl-45'),
				array('name' => '50', 'value' => 'g-pl-50'),
				array('name' => '55', 'value' => 'g-pl-55'),
				array('name' => '60', 'value' => 'g-pl-60'),
				array('name' => '65', 'value' => 'g-pl-65'),
				array('name' => '70', 'value' => 'g-pl-70'),
				array('name' => '75', 'value' => 'g-pl-75'),
				array('name' => '80', 'value' => 'g-pl-80'),
				array('name' => '85', 'value' => 'g-pl-85'),
				array('name' => '90', 'value' => 'g-pl-90'),
				array('name' => '95', 'value' => 'g-pl-95'),
				array('name' => '100', 'value' => 'g-pl-100'),
				array('name' => '105', 'value' => 'g-pl-105'),
				array('name' => '110', 'value' => 'g-pl-110'),
				array('name' => '115', 'value' => 'g-pl-115'),
				array('name' => '120', 'value' => 'g-pl-120'),
				array('name' => '125', 'value' => 'g-pl-125'),
				array('name' => '130', 'value' => 'g-pl-130'),
				array('name' => '135', 'value' => 'g-pl-135'),
				array('name' => '140', 'value' => 'g-pl-140'),
				array('name' => '145', 'value' => 'g-pl-145'),
				array('name' => '150', 'value' => 'g-pl-150'),
				array('name' => '155', 'value' => 'g-pl-155'),
				array('name' => '160', 'value' => 'g-pl-160'),
				array('name' => '165', 'value' => 'g-pl-165'),
				array('name' => '170', 'value' => 'g-pl-170')
			)
		),
		'padding-right' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_PADDING_RIGHT'),
			'property' => 'padding-right',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'g-pr-0'),
				array('name' => '1', 'value' => 'g-pr-1'),
				array('name' => '2', 'value' => 'g-pr-2'),
				array('name' => '3', 'value' => 'g-pr-3'),
				array('name' => '4', 'value' => 'g-pr-4'),
				array('name' => '5', 'value' => 'g-pr-5'),
				array('name' => '6', 'value' => 'g-pr-6'),
				array('name' => '7', 'value' => 'g-pr-7'),
				array('name' => '8', 'value' => 'g-pr-8'),
				array('name' => '9', 'value' => 'g-pr-9'),
				array('name' => '10', 'value' => 'g-pr-10'),
				array('name' => '15', 'value' => 'g-pr-15'),
				array('name' => '20', 'value' => 'g-pr-20'),
				array('name' => '25', 'value' => 'g-pr-25'),
				array('name' => '30', 'value' => 'g-pr-30'),
				array('name' => '35', 'value' => 'g-pr-35'),
				array('name' => '40', 'value' => 'g-pr-40'),
				array('name' => '45', 'value' => 'g-pr-45'),
				array('name' => '50', 'value' => 'g-pr-50'),
				array('name' => '55', 'value' => 'g-pr-55'),
				array('name' => '60', 'value' => 'g-pr-60'),
				array('name' => '65', 'value' => 'g-pr-65'),
				array('name' => '70', 'value' => 'g-pr-70'),
				array('name' => '75', 'value' => 'g-pr-75'),
				array('name' => '80', 'value' => 'g-pr-80'),
				array('name' => '85', 'value' => 'g-pr-85'),
				array('name' => '90', 'value' => 'g-pr-90'),
				array('name' => '95', 'value' => 'g-pr-95'),
				array('name' => '100', 'value' => 'g-pr-100'),
				array('name' => '105', 'value' => 'g-pr-105'),
				array('name' => '110', 'value' => 'g-pr-110'),
				array('name' => '115', 'value' => 'g-pr-115'),
				array('name' => '120', 'value' => 'g-pr-120'),
				array('name' => '125', 'value' => 'g-pr-125'),
				array('name' => '130', 'value' => 'g-pr-130'),
				array('name' => '135', 'value' => 'g-pr-135'),
				array('name' => '140', 'value' => 'g-pr-140'),
				array('name' => '145', 'value' => 'g-pr-145'),
				array('name' => '150', 'value' => 'g-pr-150'),
				array('name' => '155', 'value' => 'g-pr-155'),
				array('name' => '160', 'value' => 'g-pr-160'),
				array('name' => '165', 'value' => 'g-pr-165'),
				array('name' => '170', 'value' => 'g-pr-170')
			)
		),
		'margin-top' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_MARGIN_TOP'),
			'property' => 'margin-top',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'g-mt-0'),
				array('name' => '1', 'value' => 'g-mt-1'),
				array('name' => '2', 'value' => 'g-mt-2'),
				array('name' => '3', 'value' => 'g-mt-3'),
				array('name' => '4', 'value' => 'g-mt-4'),
				array('name' => '5', 'value' => 'g-mt-5'),
				array('name' => '6', 'value' => 'g-mt-6'),
				array('name' => '7', 'value' => 'g-mt-7'),
				array('name' => '8', 'value' => 'g-mt-8'),
				array('name' => '9', 'value' => 'g-mt-9'),
				array('name' => '10', 'value' => 'g-mt-10'),
				array('name' => '15', 'value' => 'g-mt-15'),
				array('name' => '20', 'value' => 'g-mt-20'),
				array('name' => '25', 'value' => 'g-mt-25'),
				array('name' => '30', 'value' => 'g-mt-30'),
				array('name' => '35', 'value' => 'g-mt-35'),
				array('name' => '40', 'value' => 'g-mt-40'),
				array('name' => '45', 'value' => 'g-mt-45'),
				array('name' => '50', 'value' => 'g-mt-50'),
				array('name' => '55', 'value' => 'g-mt-55'),
				array('name' => '60', 'value' => 'g-mt-60'),
				array('name' => '65', 'value' => 'g-mt-65'),
				array('name' => '70', 'value' => 'g-mt-70'),
				array('name' => '75', 'value' => 'g-mt-75'),
				array('name' => '80', 'value' => 'g-mt-80'),
				array('name' => '85', 'value' => 'g-mt-85'),
				array('name' => '90', 'value' => 'g-mt-90'),
				array('name' => '95', 'value' => 'g-mt-95'),
				array('name' => '100', 'value' => 'g-mt-100'),
				array('name' => '105', 'value' => 'g-mt-105'),
				array('name' => '110', 'value' => 'g-mt-110'),
				array('name' => '115', 'value' => 'g-mt-115'),
				array('name' => '120', 'value' => 'g-mt-120'),
				array('name' => '125', 'value' => 'g-mt-125'),
				array('name' => '130', 'value' => 'g-mt-130'),
				array('name' => '135', 'value' => 'g-mt-135'),
				array('name' => '140', 'value' => 'g-mt-140'),
				array('name' => '145', 'value' => 'g-mt-145'),
				array('name' => '150', 'value' => 'g-mt-150'),
				array('name' => '155', 'value' => 'g-mt-155'),
				array('name' => '160', 'value' => 'g-mt-160'),
				array('name' => '165', 'value' => 'g-mt-165'),
				array('name' => '170', 'value' => 'g-mt-170')
			)
		),
		'columns' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_COLUMNS_ON_ROW'),
			'property' => 'columns',
			'type' => 'slider',
			'items' => array(
				array('name' => '1', 'value' => 'col-lg-12'),
				array('name' => '2', 'value' => 'col-lg-6'),
				array('name' => '3', 'value' => 'col-lg-4'),
				array('name' => '4', 'value' => 'col-lg-3'),
				array('name' => '6', 'value' => 'col-lg-2'),
				array('name' => '12', 'value' => 'col-lg-1')
			)
		),
		'display' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_DEVICE_DISPLAY'),
			'property' => 'display',
			'type' => 'display',
			'items' => array(
				array('name' => '<span class="landing-ui-button-desktop"></span>', 'value' => 'l-d-lg-none'),
				array('name' => '<span class="landing-ui-button-tablet"></span>', 'value' => 'l-d-md-none'),
				array('name' => '<span class="landing-ui-button-mobile"></span>', 'value' => 'l-d-xs-none')
			)
		),
		'border-radius' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BORDER_RADIUS'),
			'property' => 'border-radius',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'rounded-0'),
				array('name' => '1', 'value' => 'g-rounded-1'),
				array('name' => '2', 'value' => 'g-rounded-2'),
				array('name' => '3', 'value' => 'g-rounded-3'),
				array('name' => '4', 'value' => 'g-rounded-4'),
				array('name' => '5', 'value' => 'g-rounded-5'),
				array('name' => '6', 'value' => 'g-rounded-6'),
				array('name' => '7', 'value' => 'g-rounded-7'),
				array('name' => '10', 'value' => 'g-rounded-10'),
				array('name' => '15', 'value' => 'g-rounded-15'),
				array('name' => '20', 'value' => 'g-rounded-20'),
				array('name' => '25', 'value' => 'g-rounded-25'),
				array('name' => '30', 'value' => 'g-rounded-30'),
				array('name' => '50', 'value' => 'g-rounded-50'),
				array('name' => '50%', 'value' => 'g-rounded-50x'),
			)
		),
		'border-width' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BORDER_WIDTH'),
			'property' => 'border-width',
			'type' => 'slider',
			'items' => array(
				array('name' => '0', 'value' => 'g-brd-0'),
				array('name' => '1', 'value' => 'g-brd-1'),
				array('name' => '2', 'value' => 'g-brd-2'),
				array('name' => '3', 'value' => 'g-brd-3'),
				array('name' => '4', 'value' => 'g-brd-4'),
				array('name' => '5', 'value' => 'g-brd-5'),
				array('name' => '6', 'value' => 'g-brd-6'),
				array('name' => '7', 'value' => 'g-brd-7'),
				array('name' => '10', 'value' => 'g-brd-10'),
				array('name' => '12', 'value' => 'g-brd-12'),
			)
		),
		'background-attachment' => array(
			'name' => 'tipa parallax',
			'property' => 'background-attachment',
			'type' => 'list',
			'items' => array(
				array('name' => 'NO', 'value' => 'g-bg-attachment-scroll'),
				array('name' => 'YES', 'value' => 'g-bg-attachment-fixed'),
			)
		),
		'background-overlay' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BACKGROUND_OVERLAY'),
			'property' => 'background-color',
			'pseudo-element' => '::after',
			'type' => 'palette',
			'items' => array(
				array('name' => 'g-bg-primary-opacity-0_2--after', 'value' => 'g-bg-primary-opacity-0_2--after'),
				array('name' => 'g-bg-primary-opacity-0_3--after', 'value' => 'g-bg-primary-opacity-0_3--after'),
				array('name' => 'g-bg-primary-opacity-0_4--after', 'value' => 'g-bg-primary-opacity-0_4--after'),
				array('name' => 'g-bg-primary-opacity-0_6--after', 'value' => 'g-bg-primary-opacity-0_6--after'),
				array('name' => 'g-bg-primary-opacity-0_8--after', 'value' => 'g-bg-primary-opacity-0_8--after'),
				array('name' => 'g-bg-primary-opacity-0_9--after', 'value' => 'g-bg-primary-opacity-0_9--after'),
				array('name' => 'g-bg-black-opacity-0_1--after', 'value' => 'g-bg-black-opacity-0_1--after'),
				array('name' => 'g-bg-black-opacity-0_2--after', 'value' => 'g-bg-black-opacity-0_2--after'),
				array('name' => 'g-bg-black-opacity-0_3--after', 'value' => 'g-bg-black-opacity-0_3--after'),
				array('name' => 'g-bg-black-opacity-0_4--after', 'value' => 'g-bg-black-opacity-0_4--after'),
				array('name' => 'g-bg-black-opacity-0_5--after', 'value' => 'g-bg-black-opacity-0_5--after'),
				array('name' => 'g-bg-black-opacity-0_6--after', 'value' => 'g-bg-black-opacity-0_6--after'),
				array('name' => 'g-bg-black-opacity-0_7--after', 'value' => 'g-bg-black-opacity-0_7--after'),
				array('name' => 'g-bg-black-opacity-0_8--after', 'value' => 'g-bg-black-opacity-0_8--after'),
				array('name' => 'g-bg-black-opacity-0_9--after', 'value' => 'g-bg-black-opacity-0_9--after'),
				array('name' => 'g-bg-white-opacity-0_1--after', 'value' => 'g-bg-white-opacity-0_1--after'),
				array('name' => 'g-bg-white-opacity-0_3--after', 'value' => 'g-bg-white-opacity-0_3--after'),
				array('name' => 'g-bg-white-opacity-0_5--after', 'value' => 'g-bg-white-opacity-0_5--after'),
				array('name' => 'g-bg-white-opacity-0_7--after', 'value' => 'g-bg-white-opacity-0_7--after'),
				array('name' => 'g-bg-white-opacity-0_8--after', 'value' => 'g-bg-white-opacity-0_8--after'),
				array('name' => 'g-bg-white-opacity-0_9--after', 'value' => 'g-bg-white-opacity-0_9--after'),
				
				array('name' => 'g-bg-red-opacity-0_3--after', 'value' => 'g-bg-red-opacity-0_3--after'),
				array('name' => 'g-bg-red-opacity-0_5--after', 'value' => 'g-bg-red-opacity-0_5--after'),
				array('name' => 'g-bg-red-opacity-0_7--after', 'value' => 'g-bg-red-opacity-0_7--after'),
				
				array('name' => 'g-bg-yellow-opacity-0_3--after', 'value' => 'g-bg-yellow-opacity-0_3--after'),
				array('name' => 'g-bg-yellow-opacity-0_5--after', 'value' => 'g-bg-yellow-opacity-0_5--after'),
				array('name' => 'g-bg-yellow-opacity-0_7--after', 'value' => 'g-bg-yellow-opacity-0_7--after'),
				
				array('name' => 'g-bg-green-opacity-0_3--after', 'value' => 'g-bg-green-opacity-0_3--after'),
				array('name' => 'g-bg-green-opacity-0_5--after', 'value' => 'g-bg-green-opacity-0_5--after'),
				array('name' => 'g-bg-green-opacity-0_7--after', 'value' => 'g-bg-green-opacity-0_7--after'),
				
				array('name' => 'g-bg-teal-opacity-0_3--after', 'value' => 'g-bg-teal-opacity-0_3--after'),
				array('name' => 'g-bg-teal-opacity-0_5--after', 'value' => 'g-bg-teal-opacity-0_5--after'),
				array('name' => 'g-bg-teal-opacity-0_7--after', 'value' => 'g-bg-teal-opacity-0_7--after'),
				
				array('name' => 'g-bg-cyan-opacity-0_3--after', 'value' => 'g-bg-cyan-opacity-0_3--after'),
				array('name' => 'g-bg-cyan-opacity-0_5--after', 'value' => 'g-bg-cyan-opacity-0_5--after'),
				array('name' => 'g-bg-cyan-opacity-0_7--after', 'value' => 'g-bg-cyan-opacity-0_7--after'),
				array('name' => 'g-bg-cyan-opacity-0_9--after', 'value' => 'g-bg-cyan-opacity-0_9--after'),
				
				array('name' => 'g-bg-blue-opacity-0_3--after', 'value' => 'g-bg-blue-opacity-0_3--after'),
				array('name' => 'g-bg-blue-opacity-0_5--after', 'value' => 'g-bg-blue-opacity-0_5--after'),
				array('name' => 'g-bg-blue-opacity-0_7--after', 'value' => 'g-bg-blue-opacity-0_7--after'),
				
				array('name' => 'g-bg-purple-opacity-0_3--after', 'value' => 'g-bg-purple-opacity-0_3--after'),
				array('name' => 'g-bg-purple-opacity-0_5--after', 'value' => 'g-bg-purple-opacity-0_5--after'),
				array('name' => 'g-bg-purple-opacity-0_7--after', 'value' => 'g-bg-purple-opacity-0_7--after'),
				array('name' => 'g-bg-purple-opacity-0_9--after', 'value' => 'g-bg-purple-opacity-0_9--after'),
				
				array('name' => 'g-bg-bluegray-opacity-0_2--after', 'value' => 'g-bg-bluegray-opacity-0_2--after'),
				array('name' => 'g-bg-bluegray-opacity-0_3--after', 'value' => 'g-bg-bluegray-opacity-0_3--after'),
				
				array('name' => 'g-bg-darkblue-opacity-0_3--after', 'value' => 'g-bg-darkblue-opacity-0_3--after'),
				array('name' => 'g-bg-darkblue-opacity-0_5--after', 'value' => 'g-bg-darkblue-opacity-0_5--after'),
				array('name' => 'g-bg-darkblue-opacity-0_7--after', 'value' => 'g-bg-darkblue-opacity-0_7--after'),
			)
		),
		'background-hover' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BACKGROUND_HOVER'),
			'property' => "background-color",
			'type' => 'palette',
			'pseudo-class' => ':hover',
			'items' => array(
				array('name' => 'g-bg-black--hover', 'value' => 'g-bg-black--hover'),
				array('name' => 'g-bg-black-opacity-0_3--hover', 'value' => 'g-bg-black-opacity-0_3--hover'),
				array('name' => 'g-bg-black-opacity-0_5--hover', 'value' => 'g-bg-black-opacity-0_5--hover'),
				array('name' => 'g-bg-black-opacity-0_6--hover', 'value' => 'g-bg-black-opacity-0_6--hover'),
				array('name' => 'g-bg-black-opacity-0_8--hover', 'value' => 'g-bg-black-opacity-0_8--hover'),
				array('name' => 'g-bg-black-opacity-0_9--hover', 'value' => 'g-bg-black-opacity-0_9--hover'),
				array('name' => 'g-bg-white--hover', 'value' => 'g-bg-white--hover'),
				array('name' => 'g-bg-white-opacity-0_2--hover', 'value' => 'g-bg-white-opacity-0_2--hover'),
				array('name' => 'g-bg-white-opacity-0_3--hover', 'value' => 'g-bg-white-opacity-0_3--hover'),
				array('name' => 'g-bg-white-opacity-0_4--hover', 'value' => 'g-bg-white-opacity-0_4--hover'),
				array('name' => 'g-bg-white-opacity-0_7--hover', 'value' => 'g-bg-white-opacity-0_7--hover'),
				array('name' => 'g-bg-white-opacity-0_8--hover', 'value' => 'g-bg-white-opacity-0_8--hover'),
				array('name' => 'g-bg-white-opacity-0_9--hover', 'value' => 'g-bg-white-opacity-0_9--hover'),
				array('name' => 'g-bg-gray-dark-v1--hover', 'value' => 'g-bg-gray-dark-v1--hover'),
				array('name' => 'g-bg-gray-dark-v2--hover', 'value' => 'g-bg-gray-dark-v2--hover'),
				array('name' => 'g-bg-gray-dark-v3--hover', 'value' => 'g-bg-gray-dark-v3--hover'),
				array('name' => 'g-bg-gray-dark-v4--hover', 'value' => 'g-bg-gray-dark-v4--hover'),
				array('name' => 'g-bg-gray-dark-v5--hover', 'value' => 'g-bg-gray-dark-v5--hover'),
				array('name' => 'g-bg-gray-light-v2--hover', 'value' => 'g-bg-gray-light-v2--hover'),
				array('name' => 'g-bg-gray-light-v1--hover', 'value' => 'g-bg-gray-light-v1--hover'),
				array('name' => 'g-bg-gray-light-v3--hover', 'value' => 'g-bg-gray-light-v3--hover'),
				array('name' => 'g-bg-gray-light-v4--hover', 'value' => 'g-bg-gray-light-v4--hover'),
				array('name' => 'g-bg-gray-light-v5--hover', 'value' => 'g-bg-gray-light-v5--hover'),
				array('name' => 'g-bg-transparent--hover', 'value' => 'g-bg-transparent--hover'),
				array('name' => 'g-bg-green--hover', 'value' => 'g-bg-green--hover'),
				array('name' => 'g-bg-blue--hover', 'value' => 'g-bg-blue--hover'),
				array('name' => 'g-bg-red--hover', 'value' => 'g-bg-red--hover'),
				array('name' => 'g-bg-lightred--hover', 'value' => 'g-bg-lightred--hover'),
				array('name' => 'g-bg-purple--hover', 'value' => 'g-bg-purple--hover'),
				array('name' => 'g-bg-pink--hover', 'value' => 'g-bg-pink--hover'),
				array('name' => 'g-bg-orange--hover', 'value' => 'g-bg-orange--hover'),
				array('name' => 'g-bg-deeporange--hover', 'value' => 'g-bg-deeporange--hover'),
				array('name' => 'g-bg-yellow--hover', 'value' => 'g-bg-yellow--hover'),
				array('name' => 'g-bg-aqua--hover', 'value' => 'g-bg-aqua--hover'),
				array('name' => 'g-bg-cyan--hover', 'value' => 'g-bg-cyan--hover'),
				array('name' => 'g-bg-teal--hover', 'value' => 'g-bg-teal--hover'),
				array('name' => 'g-bg-brown--hover', 'value' => 'g-bg-brown--hover'),
				array('name' => 'g-bg-bluegray--hover', 'value' => 'g-bg-bluegray--hover'),
				array('name' => 'g-bg-facebook--hover', 'value' => 'g-bg-facebook--hover'),
				array('name' => 'g-bg-twitter--hover', 'value' => 'g-bg-twitter--hover'),
				array('name' => 'g-bg-skype--hover', 'value' => 'g-bg-skype--hover'),
				array('name' => 'g-bg-pinterest--hover', 'value' => 'g-bg-pinterest--hover'),
				array('name' => 'g-bg-vine--hover', 'value' => 'g-bg-vine--hover'),
				array('name' => 'g-bg-youtube--hover', 'value' => 'g-bg-youtube--hover'),
				array('name' => 'g-bg-google-plus--hover', 'value' => 'g-bg-google-plus--hover'),
				array('name' => 'g-bg-dribbble--hover', 'value' => 'g-bg-dribbble--hover'),
				array('name' => 'g-bg-vk--hover', 'value' => 'g-bg-vk--hover'),
				array('name' => 'g-bg-linkedin--hover', 'value' => 'g-bg-linkedin--hover'),
				array('name' => 'g-bg-instagram--hover', 'value' => 'g-bg-instagram--hover'),
				array('name' => 'g-bg-primary--hover', 'value' => 'g-bg-primary--hover'),
				array('name' => 'g-bg-primary-opacity-0_2--hover', 'value' => 'g-bg-primary-opacity-0_2--hover'),
				array('name' => 'g-bg-primary-opacity-0_3--hover', 'value' => 'g-bg-primary-opacity-0_3--hover'),
				array('name' => 'g-bg-primary-opacity-0_4--hover', 'value' => 'g-bg-primary-opacity-0_4--hover'),
				array('name' => 'g-bg-primary-opacity-0_6--hover', 'value' => 'g-bg-primary-opacity-0_6--hover'),
				array('name' => 'g-bg-primary-opacity-0_8--hover', 'value' => 'g-bg-primary-opacity-0_8--hover'),
				array('name' => 'g-bg-primary-opacity-0_9--hover', 'value' => 'g-bg-primary-opacity-0_9--hover'),
				array('name' => 'g-theme-travel-bg-black-v1-opacity-0_8--hover', 'value' => 'g-theme-travel-bg-black-v1-opacity-0_8--hover'),
			)
		),
		'color-hover' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_COLOR_HOVER'),
			'property' => "color",
			'type' => 'palette',
			'pseudo-class' => ':hover',
			'items' => array(
				array('name' => 'g-color-primary--hover', 'value' => 'g-color-primary--hover'),
				array('name' => 'g-color-black--hover', 'value' => 'g-color-black--hover'),
				array('name' => 'g-color-black-opacity-0_1--hover', 'value' => 'g-color-black-opacity-0_1--hover'),
				array('name' => 'g-color-black-opacity-0_3--hover', 'value' => 'g-color-black-opacity-0_3--hover'),
				array('name' => 'g-color-black-opacity-0_5--hover', 'value' => 'g-color-black-opacity-0_5--hover'),
				array('name' => 'g-color-black-opacity-0_6--hover', 'value' => 'g-color-black-opacity-0_6--hover'),
				array('name' => 'g-color-black-opacity-0_7--hover', 'value' => 'g-color-black-opacity-0_7--hover'),
				array('name' => 'g-color-black-opacity-0_8--hover', 'value' => 'g-color-black-opacity-0_8--hover'),
				array('name' => 'g-color-black-opacity-0_9--hover', 'value' => 'g-color-black-opacity-0_9--hover'),
				array('name' => 'g-color-white--hover', 'value' => 'g-color-white--hover'),
				array('name' => 'g-color-white-opacity-0_1--hover', 'value' => 'g-color-white-opacity-0_1--hover'),
				array('name' => 'g-color-white-opacity-0_2--hover', 'value' => 'g-color-white-opacity-0_2--hover'),
				array('name' => 'g-color-white-opacity-0_3--hover', 'value' => 'g-color-white-opacity-0_3--hover'),
				array('name' => 'g-color-white-opacity-0_5--hover', 'value' => 'g-color-white-opacity-0_5--hover'),
				array('name' => 'g-color-white-opacity-0_6--hover', 'value' => 'g-color-white-opacity-0_6--hover'),
				array('name' => 'g-color-white-opacity-0_7--hover', 'value' => 'g-color-white-opacity-0_7--hover'),
				array('name' => 'g-color-white-opacity-0_9--hover', 'value' => 'g-color-white-opacity-0_9--hover'),
				array('name' => 'g-color-gray-light-v1--hover', 'value' => 'g-color-gray-light-v1--hover'),
				array('name' => 'g-color-gray-light-v2--hover', 'value' => 'g-color-gray-light-v2--hover'),
				array('name' => 'g-color-gray-light-v3--hover', 'value' => 'g-color-gray-light-v3--hover'),
				array('name' => 'g-color-gray-light-v4--hover', 'value' => 'g-color-gray-light-v4--hover'),
				array('name' => 'g-color-gray-light-v5--hover', 'value' => 'g-color-gray-light-v5--hover'),
				array('name' => 'g-color-gray-dark-v1--hover', 'value' => 'g-color-gray-dark-v1--hover'),
				array('name' => 'g-color-gray-dark-v2--hover', 'value' => 'g-color-gray-dark-v2--hover'),
				array('name' => 'g-color-gray-dark-v3--hover', 'value' => 'g-color-gray-dark-v3--hover'),
				array('name' => 'g-color-gray-dark-v4--hover', 'value' => 'g-color-gray-dark-v4--hover'),
				array('name' => 'g-color-gray-dark-v5--hover', 'value' => 'g-color-gray-dark-v5--hover'),
				array('name' => 'g-color-blue--hover', 'value' => 'g-color-blue--hover'),
				array('name' => 'g-color-lightblue--hover', 'value' => 'g-color-lightblue--hover'),
				array('name' => 'g-color-lightblue-v1--hover', 'value' => 'g-color-lightblue-v1--hover'),
				array('name' => 'g-color-darkblue--hover', 'value' => 'g-color-darkblue--hover'),
				array('name' => 'g-color-indigo--hover', 'value' => 'g-color-indigo--hover'),
				array('name' => 'g-color-red--hover', 'value' => 'g-color-red--hover'),
				array('name' => 'g-color-lightred--hover', 'value' => 'g-color-lightred--hover'),
				array('name' => 'g-color-darkred--hover', 'value' => 'g-color-darkred--hover'),
				array('name' => 'g-color-purple--hover', 'value' => 'g-color-purple--hover'),
				array('name' => 'g-color-darkpurple--hover', 'value' => 'g-color-darkpurple--hover'),
				array('name' => 'g-color-pink--hover', 'value' => 'g-color-pink--hover'),
				array('name' => 'g-color-orange--hover', 'value' => 'g-color-orange--hover'),
				array('name' => 'g-color-deeporange--hover', 'value' => 'g-color-deeporange--hover'),
				array('name' => 'g-color-yellow--hover', 'value' => 'g-color-yellow--hover'),
				array('name' => 'g-color-aqua--hover', 'value' => 'g-color-aqua--hover'),
				array('name' => 'g-color-cyan--hover', 'value' => 'g-color-cyan--hover'),
				array('name' => 'g-color-teal--hover', 'value' => 'g-color-teal--hover'),
				array('name' => 'g-color-brown--hover', 'value' => 'g-color-brown--hover'),
				array('name' => 'g-color-bluegray--hover', 'value' => 'g-color-bluegray--hover'),
				array('name' => 'g-color-facebook--hover', 'value' => 'g-color-facebook--hover'),
				array('name' => 'g-color-twitter--hover', 'value' => 'g-color-twitter--hover'),
				array('name' => 'g-color-skype--hover', 'value' => 'g-color-skype--hover'),
				array('name' => 'g-color-pinterest--hover', 'value' => 'g-color-pinterest--hover'),
				array('name' => 'g-color-vine--hover', 'value' => 'g-color-vine--hover'),
				array('name' => 'g-color-youtube--hover', 'value' => 'g-color-youtube--hover'),
				array('name' => 'g-color-google-plus--hover', 'value' => 'g-color-google-plus--hover'),
				array('name' => 'g-color-dribbble--hover', 'value' => 'g-color-dribbble--hover'),
				array('name' => 'g-color-vk--hover', 'value' => 'g-color-vk--hover'),
				array('name' => 'g-color-linkedin--hover', 'value' => 'g-color-linkedin--hover'),
				array('name' => 'g-color-instagram--hover', 'value' => 'g-color-instagram--hover'),
			)
		),
		'button-color' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_COLOR_BUTTON'),
			'property' => 'background-color',
			'type' => 'palette',
			'exclude' => 'button-outline-color',
			'items' => array(
				array('name' => 'u-btn-primary', 'value' => 'u-btn-primary'),
				array('name' => 'u-btn-white', 'value' => 'u-btn-white'),
				array('name' => 'u-btn-black', 'value' => 'u-btn-black'),
				array('name' => 'u-btn-darkgray', 'value' => 'u-btn-darkgray'),
				array('name' => 'u-btn-red', 'value' => 'u-btn-red'),
				array('name' => 'u-btn-lightred', 'value' => 'u-btn-lightred'),
				array('name' => 'u-btn-darkred', 'value' => 'u-btn-darkred'),
				array('name' => 'u-btn-blue', 'value' => 'u-btn-blue'),
				array('name' => 'u-btn-indigo', 'value' => 'u-btn-indigo'),
				array('name' => 'u-btn-purple', 'value' => 'u-btn-purple'),
				array('name' => 'u-btn-darkpurple', 'value' => 'u-btn-darkpurple'),
				array('name' => 'u-btn-pink', 'value' => 'u-btn-pink'),
				array('name' => 'u-btn-orange', 'value' => 'u-btn-orange'),
				array('name' => 'u-btn-deeporange', 'value' => 'u-btn-deeporange'),
				array('name' => 'u-btn-yellow', 'value' => 'u-btn-yellow'),
				array('name' => 'u-btn-aqua', 'value' => 'u-btn-aqua'),
				array('name' => 'u-btn-cyan', 'value' => 'u-btn-cyan'),
				array('name' => 'u-btn-teal', 'value' => 'u-btn-teal'),
				array('name' => 'u-btn-brown', 'value' => 'u-btn-brown'),
				array('name' => 'u-btn-bluegray', 'value' => 'u-btn-bluegray'),
				array('name' => 'u-btn-facebook', 'value' => 'u-btn-facebook'),
				array('name' => 'u-btn-twitter', 'value' => 'u-btn-twitter')
			)
		),
		'button-outline-color' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_COLOR_BUTTON_OUTLINE'),
			'property' => 'border-color',
			'type' => 'palette',
			'exclude' => 'button-color',
			'items' => array(
				array('name' => 'u-btn-outline-primary', 'value' => 'u-btn-outline-primary'),
				array('name' => 'u-btn-outline-white', 'value' => 'u-btn-outline-white'),
				array('name' => 'u-btn-outline-black', 'value' => 'u-btn-outline-black'),
				array('name' => 'u-btn-outline-darkgray', 'value' => 'u-btn-outline-darkgray'),
				array('name' => 'u-btn-outline-red', 'value' => 'u-btn-outline-red'),
				array('name' => 'u-btn-outline-lightred', 'value' => 'u-btn-outline-lightred'),
				array('name' => 'u-btn-outline-darkred', 'value' => 'u-btn-outline-darkred'),
				array('name' => 'u-btn-outline-blue', 'value' => 'u-btn-outline-blue'),
				array('name' => 'u-btn-outline-indigo', 'value' => 'u-btn-outline-indigo'),
				array('name' => 'u-btn-outline-purple', 'value' => 'u-btn-outline-purple'),
				array('name' => 'u-btn-outline-darkpurple', 'value' => 'u-btn-outline-darkpurple'),
				array('name' => 'u-btn-outline-pink', 'value' => 'u-btn-outline-pink'),
				array('name' => 'u-btn-outline-orange', 'value' => 'u-btn-outline-orange'),
				array('name' => 'u-btn-outline-deeporange', 'value' => 'u-btn-outline-deeporange'),
				array('name' => 'u-btn-outline-yellow', 'value' => 'u-btn-outline-yellow'),
				array('name' => 'u-btn-outline-aqua', 'value' => 'u-btn-outline-aqua'),
				array('name' => 'u-btn-outline-cyan', 'value' => 'u-btn-outline-cyan'),
				array('name' => 'u-btn-outline-teal', 'value' => 'u-btn-outline-teal'),
				array('name' => 'u-btn-outline-brown', 'value' => 'u-btn-outline-brown'),
				array('name' => 'u-btn-outline-bluegray', 'value' => 'u-btn-outline-bluegray'),
				array('name' => 'u-btn-outline-facebook', 'value' => 'u-btn-outline-facebook'),
				array('name' => 'u-btn-outline-twitter', 'value' => 'u-btn-outline-twitter')
			)
		),
		'background-color-before' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_BG_COLOR_BEFORE'),
			'property' => 'background-color',
			'pseudo-element' => '::before',
			'type' => 'palette',
			'items' => array(
				array('name' => 'g-bg-primary--before', 'value' => 'g-bg-primary--before'),
				array('name' => 'g-bg-primary-opacity-0_1--before', 'value' => 'g-bg-primary-opacity-0_1--before'),
				array('name' => 'g-bg-primary-opacity-0_2--before', 'value' => 'g-bg-primary-opacity-0_2--before'),
				array('name' => 'g-bg-primary-opacity-0_3--before', 'value' => 'g-bg-primary-opacity-0_3--before'),
				array('name' => 'g-bg-primary-opacity-0_4--before', 'value' => 'g-bg-primary-opacity-0_4--before'),
				array('name' => 'g-bg-primary-opacity-0_6--before', 'value' => 'g-bg-primary-opacity-0_6--before'),
				array('name' => 'g-bg-primary-opacity-0_8--before', 'value' => 'g-bg-primary-opacity-0_8--before'),
				array('name' => 'g-bg-primary-opacity-0_9--before', 'value' => 'g-bg-primary-opacity-0_9--before'),
				array('name' => 'g-bg-bluegray--before', 'value' => 'g-bg-bluegray--before'),
				array('name' => 'g-bg-bluegray-opacity-0_2--before', 'value' => 'g-bg-bluegray-opacity-0_2--before'),
				array('name' => 'g-bg-bluegray-opacity-0_3--before', 'value' => 'g-bg-bluegray-opacity-0_3--before'),
				array('name' => 'g-bg-black--before', 'value' => 'g-bg-black--before'),
				array('name' => 'g-bg-black-opacity-0_1--before', 'value' => 'g-bg-black-opacity-0_1--before'),
				array('name' => 'g-bg-black-opacity-0_2--before', 'value' => 'g-bg-black-opacity-0_2--before'),
				array('name' => 'g-bg-black-opacity-0_3--before', 'value' => 'g-bg-black-opacity-0_3--before'),
				array('name' => 'g-bg-black-opacity-0_4--before', 'value' => 'g-bg-black-opacity-0_4--before'),
				array('name' => 'g-bg-black-opacity-0_5--before', 'value' => 'g-bg-black-opacity-0_5--before'),
				array('name' => 'g-bg-black-opacity-0_6--before', 'value' => 'g-bg-black-opacity-0_6--before'),
				array('name' => 'g-bg-black-opacity-0_7--before', 'value' => 'g-bg-black-opacity-0_7--before'),
				array('name' => 'g-bg-black-opacity-0_8--before', 'value' => 'g-bg-black-opacity-0_8--before'),
				array('name' => 'g-bg-black-opacity-0_9--before', 'value' => 'g-bg-black-opacity-0_9--before'),
				array('name' => 'g-bg-white--before', 'value' => 'g-bg-white--before'),
				array('name' => 'g-bg-white-opacity-0_1--before', 'value' => 'g-bg-white-opacity-0_1--before'),
				array('name' => 'g-bg-white-opacity-0_2--before', 'value' => 'g-bg-white-opacity-0_2--before'),
				array('name' => 'g-bg-white-opacity-0_3--before', 'value' => 'g-bg-white-opacity-0_3--before'),
				array('name' => 'g-bg-white-opacity-0_4--before', 'value' => 'g-bg-white-opacity-0_4--before'),
				array('name' => 'g-bg-white-opacity-0_5--before', 'value' => 'g-bg-white-opacity-0_5--before'),
				array('name' => 'g-bg-white-opacity-0_7--before', 'value' => 'g-bg-white-opacity-0_7--before'),
				array('name' => 'g-bg-white-opacity-0_8--before', 'value' => 'g-bg-white-opacity-0_8--before'),
				array('name' => 'g-bg-white-opacity-0_9--before', 'value' => 'g-bg-white-opacity-0_9--before'),
				array('name' => 'g-bg-gray-dark-v1--before', 'value' => 'g-bg-gray-dark-v1--before'),
				array('name' => 'g-bg-gray-dark-v2--before', 'value' => 'g-bg-gray-dark-v2--before'),
				array('name' => 'g-bg-gray-dark-v3--before', 'value' => 'g-bg-gray-dark-v3--before'),
				array('name' => 'g-bg-gray-dark-v4--before', 'value' => 'g-bg-gray-dark-v4--before'),
				array('name' => 'g-bg-gray-dark-v5--before', 'value' => 'g-bg-gray-dark-v5--before'),
				array('name' => 'g-bg-gray-light-v1--before', 'value' => 'g-bg-gray-light-v1--before'),
				array('name' => 'g-bg-gray-light-v2--before', 'value' => 'g-bg-gray-light-v2--before'),
				array('name' => 'g-bg-gray-light-v3--before', 'value' => 'g-bg-gray-light-v3--before'),
				array('name' => 'g-bg-gray-light-v4--before', 'value' => 'g-bg-gray-light-v4--before'),
				array('name' => 'g-bg-gray-light-v5--before', 'value' => 'g-bg-gray-light-v5--before'),
				array('name' => 'g-bg-beige--before', 'value' => 'g-bg-beige--before'),
				array('name' => 'g-bg-green--before', 'value' => 'g-bg-green--before'),
				array('name' => 'g-bg-blue--before', 'value' => 'g-bg-blue--before'),
				array('name' => 'g-bg-lightblue--before', 'value' => 'g-bg-lightblue--before'),
				array('name' => 'g-bg-lightblue-v1--before', 'value' => 'g-bg-lightblue-v1--before'),
				array('name' => 'g-bg-darkblue--before', 'value' => 'g-bg-darkblue--before'),
				array('name' => 'g-bg-indigo--before', 'value' => 'g-bg-indigo--before'),
				array('name' => 'g-bg-red--before', 'value' => 'g-bg-red--before'),
				array('name' => 'g-bg-lightred--before', 'value' => 'g-bg-lightred--before'),
				array('name' => 'g-bg-darkred--before', 'value' => 'g-bg-darkred--before'),
				array('name' => 'g-bg-purple--before', 'value' => 'g-bg-purple--before'),
				array('name' => 'g-bg-darkpurple--before', 'value' => 'g-bg-darkpurple--before'),
				array('name' => 'g-bg-pink--before', 'value' => 'g-bg-pink--before'),
				array('name' => 'g-bg-orange--before', 'value' => 'g-bg-orange--before'),
				array('name' => 'g-bg-deeporange--before', 'value' => 'g-bg-deeporange--before'),
				array('name' => 'g-bg-yellow--before', 'value' => 'g-bg-yellow--before'),
				array('name' => 'g-bg-aqua--before', 'value' => 'g-bg-aqua--before'),
				array('name' => 'g-bg-cyan--before', 'value' => 'g-bg-cyan--before'),
				array('name' => 'g-bg-teal--before', 'value' => 'g-bg-teal--before'),
				array('name' => 'g-bg-brown--before', 'value' => 'g-bg-brown--before'),
			)
		),
		'animation' => array(
			'name' => Loc::getMessage('LANDING_BLOCK_STYLE_ANIMATION'),
			'property' => 'animation-name',
			'type' => 'list',
			'items' => array(
				array('name' => Loc::getMessage('LANDING_BLOCK_STYLE_ANIMATION_NONE'), 'value' => 'animation-none'),
				array('name' => 'bounce', 'value' => 'bounce'),
				array('name' => 'flash', 'value' => 'flash'),
				array('name' => 'pulse', 'value' => 'pulse'),
				array('name' => 'rubberBand', 'value' => 'rubberBand'),
				array('name' => 'shake', 'value' => 'shake'),
				array('name' => 'headShake', 'value' => 'headShake'),
				array('name' => 'swing', 'value' => 'swing'),
				array('name' => 'tada', 'value' => 'tada'),
				array('name' => 'wobble', 'value' => 'wobble'),
				array('name' => 'jello', 'value' => 'jello'),
				array('name' => 'bounceIn', 'value' => 'bounceIn'),
				array('name' => 'bounceInDown', 'value' => 'bounceInDown'),
				array('name' => 'bounceInLeft', 'value' => 'bounceInLeft'),
				array('name' => 'bounceInRight', 'value' => 'bounceInRight'),
				array('name' => 'bounceInUp', 'value' => 'bounceInUp'),
				array('name' => 'fadeIn', 'value' => 'fadeIn'),
				array('name' => 'fadeInDown', 'value' => 'fadeInDown'),
				array('name' => 'fadeInDownBig', 'value' => 'fadeInDownBig'),
				array('name' => 'fadeInLeft', 'value' => 'fadeInLeft'),
				array('name' => 'fadeInLeftBig', 'value' => 'fadeInLeftBig'),
				array('name' => 'fadeInRight', 'value' => 'fadeInRight'),
				array('name' => 'fadeInRightBig', 'value' => 'fadeInRightBig'),
				array('name' => 'fadeInUp', 'value' => 'fadeInUp'),
				array('name' => 'fadeInUpBig', 'value' => 'fadeInUpBig'),
				array('name' => 'flip', 'value' => 'flip'),
				array('name' => 'flipInX', 'value' => 'flipInX'),
				array('name' => 'flipInY', 'value' => 'flipInY'),
				array('name' => 'lightSpeedIn', 'value' => 'lightSpeedIn'),
				array('name' => 'rotateIn', 'value' => 'rotateIn'),
				array('name' => 'rotateInDownLeft', 'value' => 'rotateInDownLeft'),
				array('name' => 'rotateInDownRight', 'value' => 'rotateInDownRight'),
				array('name' => 'rotateInUpLeft', 'value' => 'rotateInUpLeft'),
				array('name' => 'rotateInUpRight', 'value' => 'rotateInUpRight'),
				array('name' => 'rollIn', 'value' => 'rollIn'),
				array('name' => 'zoomIn', 'value' => 'zoomIn'),
				array('name' => 'zoomToIn', 'value' => 'zoomToIn'),
				array('name' => 'zoomInDown', 'value' => 'zoomInDown'),
				array('name' => 'zoomInLeft', 'value' => 'zoomInLeft'),
				array('name' => 'zoomInRight', 'value' => 'zoomInRight'),
				array('name' => 'zoomInUp', 'value' => 'zoomInUp'),
				array('name' => 'slideInDown', 'value' => 'slideInDown'),
				array('name' => 'slideInLeft', 'value' => 'slideInLeft'),
				array('name' => 'slideInRight', 'value' => 'slideInRight'),
				array('name' => 'slideInUp', 'value' => 'slideInUp'),
			)
		),
	),
	'group' => array(
		'block-default' => array(
			"display", "padding-top", "padding-bottom", "padding-left", "padding-right", "margin-top",
			"background-color", "background-gradient"
		),
		'block-default-background-overlay' => array(
			"display", "padding-top", "padding-bottom", "padding-left", "padding-right", "margin-top",  "background-overlay"
		),
		'block-default-wo-background' => array(
			"display", "padding-top", "padding-bottom", "padding-left", "padding-right", "margin-top"
		),
		'typo' => array(
			'text-align', 'color', 'font-size', 'font-family',
			'text-transform', 'line-height', 'letter-spacing', 'text-shadow'
		),
		'box' => array(
			'background-color', 'background-gradient', 'box-shadow', 'opacity', 'padding-top', 'padding-bottom'
		),
		'button' => array(
			'button-color', 'button-outline-color', 'border-width', 'color', 'font-size', 'border-radius',
		)
	)
);





