<?php
if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}
/**
 * @var array $arParams
 * @var array $arResult
 * @var $APPLICATION
 * @var $component
 * @var $templateFolder
 */

use Bitrix\Main\Localization\Loc;
?>

<div class="sn-spaces__list-anchor" id="socialnetwork-spaces-list-anchor">

</div>

<script type="text/javascript">
	BX.ready(function() {
		BX.message({
			SOCIALNETWORK_SPACES_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_FILTER_MODE_MY_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_FILTER_MODE_MY_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_FILTER_MODE_MY_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_FILTER_MODE_MY_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_FILTER_MODE_OTHER_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_FILTER_MODE_OTHER_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_FILTER_MODE_OTHER_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_FILTER_MODE_OTHER_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_FILTER_MODE_ALL_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_FILTER_MODE_ALL_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_FILTER_MODE_ALL_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_FILTER_MODE_ALL_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_MODE_POPUP_NEW_SPACE_BUTTON: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_MODE_POPUP_NEW_SPACE_BUTTON') ?>',
			SOCIALNETWORK_SPACES_LIST_MODE_POPUP_BOTTOM_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_MODE_POPUP_BOTTOM_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_SEARCH_INPUT_PLACEHOLDER: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SEARCH_INPUT_PLACEHOLDER') ?>',
			SOCIALNETWORK_SPACES_LIST_RECENT_SEARCH_LIST_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_RECENT_SEARCH_LIST_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_SEARCH_LIST_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SEARCH_LIST_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_ADD_SPACE_ITEM_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_ADD_SPACE_ITEM_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_ADD_SPACE_ITEM_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_ADD_SPACE_ITEM_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_ADD_SPACE_FORM_NAME_PLACEHOLDER: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_ADD_SPACE_FORM_NAME_PLACEHOLDER') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_OPEN_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_OPEN_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_OPEN_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_OPEN_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_CLOSED_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_CLOSED_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_CLOSED_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_CLOSED_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_SECRET_TITLE: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_SECRET_TITLE') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_SECRET_DESCRIPTION: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_SECRET_DESCRIPTION') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_HINT: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_SPACE_VIEW_MODE_HINT') ?>',
			SOCIALNETWORK_SPACES_LIST_JOIN_SPACE_BUTTON: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_JOIN_SPACE_BUTTON') ?>',
			SOCIALNETWORK_SPACES_LIST_ACCEPT_INVITATION_BUTTON: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_ACCEPT_INVITATION_BUTTON') ?>',
			SOCIALNETWORK_SPACES_LIST_DECLINE_INVITATION_BUTTON: '<?= GetMessageJS('SOCIALNETWORK_SPACES_LIST_DECLINE_INVITATION_BUTTON') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_OPEN: '<?= Loc::getMessage('SOCIALNETWORK_SPACES_LIST_SPACE_OPEN') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_PIN: '<?= Loc::getMessage('SOCIALNETWORK_SPACES_LIST_SPACE_PIN') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_UNPIN: '<?= Loc::getMessage('SOCIALNETWORK_SPACES_LIST_SPACE_UNPIN') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_FOLLOW: '<?= Loc::getMessage('SOCIALNETWORK_SPACES_LIST_SPACE_FOLLOW') ?>',
			SOCIALNETWORK_SPACES_LIST_SPACE_UNFOLLOW: '<?= Loc::getMessage('SOCIALNETWORK_SPACES_LIST_SPACE_UNFOLLOW') ?>',
			SOCIALNETWORK_SPACES_LIST_NAME_ALREADY_EXISTS_ERROR: '<?= Loc::getMessage('SOCIALNETWORK_SPACES_LIST_NAME_ALREADY_EXISTS_ERROR') ?>',
		});

		const spaceList = new BX.Socialnetwork.Spaces.List({
			recentSpaceIds: <?= CUtil::PhpToJSObject($arResult['RECENT_SPACE_IDS']) ?>,
			spaces: <?= CUtil::PhpToJSObject($arResult['SPACES']) ?>,
			invitationSpaceIds: <?= CUtil::PhpToJSObject($arResult['INVITATION_SPACE_IDS']) ?>,
			invitations: <?= CUtil::PhpToJSObject($arResult['INVITATIONS']) ?>,
			avatarColors: <?= CUtil::PhpToJSObject($arResult['AVATAR_COLORS']) ?>,

			selectedSpaceId: <?= CUtil::PhpToJSObject($arResult['SELECTED_SPACE_ID']) ?>,
			filterMode: <?= CUtil::PhpToJSObject($arResult['FILTER_MODE']) ?>,
			spacesListMode: <?= CUtil::PhpToJSObject($arResult['SPACES_LIST_MODE']) ?>,
			canCreateGroup: <?= CUtil::PhpToJSObject($arResult['CAN_CREATE_GROUP']) ?>,

			pathToUserSpace: <?= CUtil::PhpToJSObject($arResult['PATH_TO_USER_SPACE']) ?>,
			pathToGroupSpace: <?= CUtil::PhpToJSObject($arResult['PATH_TO_GROUP_SPACE']) ?>,
			currentUserId: <?= \Bitrix\Socialnetwork\Helper\User::getCurrentUserId() ?>,
		});

		spaceList.create(document.getElementById('socialnetwork-spaces-list-anchor'));
	});
</script>