<?php

if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true)
{
	die();
}
use Bitrix\Main\Localization\Loc;

Loc::loadLanguageFile($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/socialnetwork/install/js/socialnetwork/commentaux/config.php');
Loc::loadLanguageFile($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/socialnetwork/lib/commentaux/createentity.php');
Loc::loadLanguageFile($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/socialnetwork/lib/commentaux/createtask.php');

$userPage = \Bitrix\Main\Config\Option::get('socialnetwork', 'user_page', SITE_DIR . 'company/personal/');

$langAdditional = [
	'SONET_EXT_COMMENTAUX_USER_PATH' => $userPage . 'user/#user_id#/',
	'SONET_EXT_COMMENTAUX_CREATE_TASK_PATH' => $userPage . 'user/#user_id#/tasks/task/view/#task_id#/',

	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_BLOG_POST_2' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_BLOG_POST_2'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_TASK' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_TASK'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_FORUM_TOPIC' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_FORUM_TOPIC'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_CALENDAR_EVENT' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_CALENDAR_EVENT'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_TIMEMAN_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_TIMEMAN_ENTRY'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_TIMEMAN_REPORT' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_TIMEMAN_REPORT'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_LOG_ENTRY_2' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_LOG_ENTRY_2'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_PHOTO_ALBUM' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_PHOTO_ALBUM'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_PHOTO_PHOTO' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_PHOTO_PHOTO'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_WIKI' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_WIKI'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_LISTS_NEW_ELEMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_LISTS_NEW_ELEMENT'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_INTRANET_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_INTRANET_NEW_USER'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_POST_BITRIX24_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_POST_BITRIX24_NEW_USER'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_BLOG_COMMENT_2' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_BLOG_COMMENT_2'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_TASK' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_TASK'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_CALENDAR' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_CALENDAR'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_FORUM_TOPIC' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_FORUM_TOPIC'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_TIMEMAN_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_TIMEMAN_ENTRY'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_TIMEMAN_REPORT' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_TIMEMAN_REPORT'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_PHOTO_PHOTO' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_PHOTO_PHOTO'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_WIKI' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_WIKI'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_FORUM_POST_LISTS_NEW_ELEMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_FORUM_POST_LISTS_NEW_ELEMENT'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_LOG_COMMENT_2' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_LOG_COMMENT_2'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_LOG_COMMENT_INTRANET_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_LOG_COMMENT_INTRANET_NEW_USER'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_COMMENT_LOG_COMMENT_BITRIX24_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_COMMENT_LOG_COMMENT_BITRIX24_NEW_USER'),

	'SONET_COMMENTAUX_JS_CREATETASK_POST_BLOG_POST' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_BLOG_POST'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_BLOG_POST_2' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_BLOG_POST_2'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_TASK' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_TASK'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_FORUM_TOPIC' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_FORUM_TOPIC'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_CALENDAR_EVENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_CALENDAR_EVENT'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_TIMEMAN_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_TIMEMAN_ENTRY'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_TIMEMAN_REPORT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_TIMEMAN_REPORT'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_LOG_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_LOG_ENTRY'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_LOG_ENTRY_2' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_LOG_ENTRY_2'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_PHOTO_ALBUM' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_PHOTO_ALBUM'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_PHOTO_PHOTO' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_PHOTO_PHOTO'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_WIKI' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_WIKI'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_LISTS_NEW_ELEMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_LISTS_NEW_ELEMENT'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_INTRANET_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_INTRANET_NEW_USER'),
	'SONET_COMMENTAUX_JS_CREATETASK_POST_BITRIX24_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_BITRIX24_NEW_USER'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_BLOG_COMMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_BLOG_COMMENT'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_BLOG_COMMENT_2' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_BLOG_COMMENT_2'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_TASK' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_TASK'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_CALENDAR' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_CALENDAR'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_FORUM_TOPIC' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_FORUM_TOPIC'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_ENTRY'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_REPORT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_REPORT'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_PHOTO_PHOTO' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_PHOTO_PHOTO'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_WIKI' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_WIKI'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_LISTS_NEW_ELEMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_LISTS_NEW_ELEMENT'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_LOG_COMMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_LOG_COMMENT'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_LOG_COMMENT_2' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_LOG_COMMENT_2'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_LOG_COMMENT_INTRANET_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_LOG_COMMENT_INTRANET_NEW_USER'),
	'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_LOG_COMMENT_BITRIX24_NEW_USER' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_LOG_COMMENT_BITRIX24_NEW_USER'),

	'SONET_COMMENTAUX_JS_CREATEENTITY_ENTITY_CREATED_TASK' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_ENTITY_CREATED_TASK'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_ENTITY_CREATED_BLOG_POST' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_ENTITY_CREATED_BLOG_POST'),
	'SONET_COMMENTAUX_JS_CREATEENTITY_ENTITY_CREATED_CALENDAR_EVENT' => Loc::getMessage('SONET_COMMENTAUX_CREATEENTITY_ENTITY_CREATED_CALENDAR_EVENT'),
];

$moduleEvent = new \Bitrix\Main\Event(
	'socialnetwork',
	'onCommentAuxInitJs',
	[]
);
$moduleEvent->send();

foreach ($moduleEvent->getResults() as $moduleEventResult)
{
	if ($moduleEventResult->getType() === \Bitrix\Main\EventResult::SUCCESS)
	{
		$moduleEventParams = $moduleEventResult->getParameters();
		if (
			is_array($moduleEventParams)
			&& !empty($moduleEventParams['lang_additional'])
		)
		{
			$langAdditional = array_merge($langAdditional, $moduleEventParams['lang_additional']);
		}
		break;
	}
}

return [
	'js' => './dist/commentaux.bundle.js',
	'lang_additional' => $langAdditional,
	'rel' => [
		'main.core',
		'socialnetwork.renderparts',
	],
	'skip_core' => false,
];
