export type AnalyticsOptions = {
	event: string,
	tool: string,
	category: string,
	c_section?: string,
	c_sub_section?: string,
	c_element?: string,
	type?: string,
	p1?: string,
	p2?: string,
	p3?: string,
	p4?: string,
	p5?: string,
	status?: 'success' | 'error' | 'attempt' | 'cancel',
};
