<?
$support_default_option = array(
	"SUPPORT_DIR"					=> "#SITE_DIR#support/",
	"SUPPORT_EDIT"					=> "",
	"SUPPORT_MAX_FILESIZE"			=> "300",
	"ONLINE_INTERVAL"				=> "300",
	"DEFAULT_VALUE_HIDDEN"			=> "N",
	"NOT_IMAGE_EXTENSION_SUFFIX"	=> "_",
	"NOT_IMAGE_UPLOAD_DIR"			=> "support/not_image",
	"DEFAULT_AUTO_CLOSE_DAYS"		=> "7",
	"MAX_FILESIZE"					=> "0",
	"VIEW_TICKET_DEFAULT_MODE"		=> "view",
	"ONLINE_AUTO_REFRESH"			=> "60",
	"TICKETS_PER_PAGE"				=> "50",
	"SHOW_COMMENTS_IN_TICKET_LIST"  => "Y",
	"MESSAGES_PER_PAGE"				=> "50",
	"SUPERTICKET_COUPON_FORMAT"		=> "SUP-COU-##########",
	"SOURCE_MAIL"					=> "email",
	"SUPPORT_OLD_FUNCTIONALITY"		=> "Y",
	"SUPPORT_DEFAULT_SLA_ID"		=> 1,
	"SUPPORT_CACHE_DAYS_BACKWARD"	=> 50,
	"SUPPORT_CACHE_DAYS_FORWARD"	=> 50,
	);
?>