<?
global $MESS;

$MESS["SPCP_DTITLE"] = "Ukreximbank";
$MESS["SPCP_DDESCR"] = "<a href=\"http://www.eximb.com\" target=\"_blank\">Ukreximbank</a>";
$MESS["MERCH_NAME"] = "Name of your Internet store";
$MESS["MERCH_NAME_DESCR"] = "";
$MESS["MERCH_URL"] = "Address of your store";
$MESS["MERCH_URL_DESCR"] = "";
$MESS["MERCHANT"] = "Store ID";
$MESS["MERCHANT_DESCR"] = "Store ID from bank (MERCHANT)";
$MESS["TERMINAL"] = "V-POS terminal ID";
$MESS["TERMINAL_DESCR"] = "V-POS terminal ID received from bank (TERMINAL)";
$MESS["MAC"] = "MAC-key ";
$MESS["MAC_DESCR"] = "MAC-key, received from bank.  To test, use 00112233445566778899AABBCCDDEEFF";
$MESS["ORDER_DESC"] = "Order description";
$MESS["ORDER_DESC_DESCR"] = "";
$MESS["ORDER_DESC_VAL"] = "Payment order No.";
$MESS["EMAIL"] = "E-mail of Internet store";
$MESS["EMAIL_DESCR"] = "E-mail for receiving transaction notifications";
$MESS["SHOP_RESULT"] = "Address of results page";
$MESS["SHOP_RESULT_DESCR"] = "Address of page on your site where bank can receive notification concerning results of authorizations";
$MESS["ORDER_ID"] = "Order ID";
$MESS["SHOULD_PAY"] = "Order amount";
$MESS["SHOULD_PAY_DESCR"] = "Amount to be paid";
$MESS["CURRENCY"] = "Currency";
$MESS["CURRENCY_DESCR"] = "Currency description";
$MESS["IS_TEST"] = "Test regime";
$MESS["IS_TEST_DESCR"] = "If empty – the store will work in the usual regime";
$MESS["PAY_BUTTON"] = "Pay";
$MESS["EXTCODE"] = "Expanded report";
$MESS["EXTCODE_AS_FAIL"] = "The card was not authenticated by its issuing bank";
$MESS["EXTCODE_UNAVAIL"] = "The client’s bank cannot pass authentication";
$MESS["EXTCODE_AS_ERROR"] = "Technical failure in 3D authentication";
$MESS["ERROR_CHECKSUM"] = "The checksum does not match";
$MESS["ERROR_SUM"] = "Order amount invalid";
$MESS["ERROR_FROM_SERVER"] = "Payment for Order ¹#ID# was not successful. Please confirm the data entered and try to pay the order again.";
$MESS["PAYMENT_OK"] = "Payment for Order ¹#ID# has been made successfully.  Your order is paid and will be shipped soon.";
$MESS["ALLOW_DELIVERY"] = "Allow delivery";
$MESS["ALLOW_DELIVERY_DESCR"] = "If Y, then delivery will be approved upon reception of payment";
$MESS["PAY_OK"] = "Message concerning successful payment";
$MESS["PAY_OK_DESCR"] = "Enter a message which will be visible to users when returning to the site after successful payment.";
$MESS["PAY_ERROR"] = "Message concerning error in payment";
$MESS["PAY_ERROR_DESCR"] = "Enter a message which will be visible to users when returning to the site after an error in payment has occurred.";
?>
