import './application/pay-system';
import './application/payment';
import './payment-system/payment-info/button'
import './payment-system/payment-info/pay-system-small-card'
import './payment-system/button'
import './payment-system/check'
import './payment-system/error-box'
import './payment-system/pay-system-list'
import './payment-system/pay-system-result'
import './payment-system/pay-system-row'
import './payment-system/payment-info'
import './payment-system/reset-panel'
import './payment-system/backdrop'
import './payment-system/popup'