
CREATE TABLE b_search_phrase (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  TIMESTAMP_X timestamp NOT NULL,
  SITE_ID char(2) NOT NULL,
  RESULT_COUNT int NOT NULL,
  PAGES int NOT NULL,
  SESSION_ID varchar(32) NOT NULL,
  PHRASE varchar(250),
  TAGS varchar(250),
  URL_TO text,
  URL_TO_404 char(1),
  URL_TO_SITE_ID char(2),
  STAT_SESS_ID int,
  EVENT1 varchar(50),
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_search_phrase_session_id_phrase ON b_search_phrase (session_id, phrase);
CREATE INDEX ix_b_search_phrase_session_id_tags ON b_search_phrase (session_id, tags);
CREATE INDEX ix_b_search_phrase_timestamp_x ON b_search_phrase (timestamp_x);
