<?
$DB->Query("DELETE FROM b_event_type WHERE EVENT_NAME in ('ADV_BANNER_STATUS_CHANGE', 'ADV_CONTRACT_INFO')");
$DB->Query("DELETE FROM b_event_message WHERE EVENT_NAME in ('ADV_BANNER_STATUS_CHANGE', 'ADV_CONTRACT_INFO')");
?>
