export const DumbData = {
	providerData: [
		{
			'id': 136,
			'entityId': 'im-chat',
			'title': 'Dumb chat',
			'customData': {
				'imChat': {
					'ID': 136,
					'NAME': 'Dumb chat',
					'OWNER': 1,
					'EXTRANET': false,
					'AVATAR': '',
					'COLOR': '#1eb4aa',
					'TYPE': 'chat',
					'COUNTER': 0,
					'USER_COUNTER': 3,
					'MESSAGE_COUNT': 9,
					'UNREAD_ID': 0,
					'RESTRICTIONS': {
						'AVATAR': true,
						'RENAME': true,
						'EXTEND': true,
						'CALL': true,
						'MUTE': true,
						'LEAVE': true,
						'LEAVE_OWNER': true,
						'SEND': true,
						'USER_LIST': true
					},
					'LAST_MESSAGE_ID': 1173,
					'DISK_FOLDER_ID': 0,
					'ENTITY_TYPE': '',
					'ENTITY_ID': '',
					'ENTITY_DATA_1': '',
					'ENTITY_DATA_2': '',
					'ENTITY_DATA_3': '',
					'MUTE_LIST': [],
					'DATE_CREATE': '2022-04-22T16:21:51+02:00',
					'MESSAGE_TYPE': 'C',
					'PUBLIC': ''
				}
			},
			'entityType': 'GROUP',
			'avatar': '',
			'contextSort': 1_656_593_149
		},
		{
			'id': 193,
			'entityId': 'im-chat',
			'title': 'dumb channel',
			'customData': {
				'imChat': {
					'ID': 193,
					'NAME': 'dumb channel',
					'OWNER': 1,
					'EXTRANET': false,
					'AVATAR': '',
					'COLOR': '#ab7761',
					'TYPE': 'open',
					'COUNTER': 0,
					'USER_COUNTER': 1,
					'MESSAGE_COUNT': 1,
					'UNREAD_ID': 0,
					'RESTRICTIONS': {
						'AVATAR': true,
						'RENAME': true,
						'EXTEND': true,
						'CALL': true,
						'MUTE': true,
						'LEAVE': true,
						'LEAVE_OWNER': true,
						'SEND': true,
						'USER_LIST': true
					},
					'LAST_MESSAGE_ID': 1315,
					'DISK_FOLDER_ID': 0,
					'ENTITY_TYPE': '',
					'ENTITY_ID': '',
					'ENTITY_DATA_1': '',
					'ENTITY_DATA_2': '',
					'ENTITY_DATA_3': '',
					'MUTE_LIST': [],
					'DATE_CREATE': '2022-06-23T17:19:28+02:00',
					'MESSAGE_TYPE': 'O',
					'PUBLIC': ''
				}
			},
			'entityType': 'CHANNEL',
			'avatar': '',
			'contextSort': 1_657_204_502
		},
		{
			'id': 33,
			'entityId': 'im-chat',
			'title': 'sand guest #11 - OL bitrix',
			'customData': {
				'imChat': {
					'ID': 33,
					'NAME': 'sand guest #11 - OL bitrix',
					'OWNER': 0,
					'EXTRANET': false,
					'AVATAR': '',
					'COLOR': '#ba9c7b',
					'TYPE': 'lines',
					'COUNTER': 0,
					'USER_COUNTER': 1,
					'MESSAGE_COUNT': 12,
					'UNREAD_ID': 0,
					'RESTRICTIONS': {
						'AVATAR': true,
						'RENAME': true,
						'EXTEND': true,
						'CALL': true,
						'MUTE': true,
						'LEAVE': true,
						'LEAVE_OWNER': true,
						'SEND': true,
						'USER_LIST': true
					},
					'LAST_MESSAGE_ID': 478,
					'DISK_FOLDER_ID': 48,
					'ENTITY_TYPE': 'LINES',
					'ENTITY_ID': 'livechat|1|32|7',
					'ENTITY_DATA_1': 'Y|NONE|0|N|N|0|1646297379|0|0|0',
					'ENTITY_DATA_2': '',
					'ENTITY_DATA_3': 'N',
					'MUTE_LIST': [],
					'DATE_CREATE': '2022-03-03T10:49:39+02:00',
					'MESSAGE_TYPE': 'L',
					'PUBLIC': ''
				}
			},
			'entityType': 'LINES',
			'avatar': '',
			'contextSort': 1_655_302_286
		},
		{
			'id': 18,
			'entityId': 'user',
			'title': 'Viktor Viktorov',
			'customData': {
				'name': 'Viktor',
				'lastName': 'Viktorov',
				'secondName': 'Vasiliev',
				'email': 'vitya@test.ru',
				'login': 'vitya@test.ru',
				'imUser': {
					'ID': 18,
					'ACTIVE': true,
					'NAME': 'Viktor Viktorov',
					'FIRST_NAME': 'Viktor',
					'LAST_NAME': 'Viktorov',
					'WORK_POSITION': '',
					'COLOR': '#f76187',
					'AVATAR': '/upload/resize_cache/main/657/bkpztpgu3jsebk09d5iorqfmj3q2lr6o/200_200_2/1.png',
					'GENDER': 'M',
					'BIRTHDAY': '04-07',
					'EXTRANET': false,
					'NETWORK': false,
					'BOT': false,
					'CONNECTOR': false,
					'EXTERNAL_AUTH_ID': 'default',
					'STATUS': 'online',
					'IDLE': false,
					'LAST_ACTIVITY_DATE': '2022-03-18T14:40:44+02:00',
					'MOBILE_LAST_DATE': false,
					'ABSENT': false,
					'DEPARTMENTS': [
						1
					],
					'PHONES': false
				}
			},
			'tabs': [
				'user'
			],
			'entityType': 'employee',
			'avatar': '/upload/resize_cache/main/657/bkpztpgu3jsebk09d5iorqfmj3q2lr6o/200_200_2/1.png',
			'contextSort': 1_657_205_648,
			'globalSort': 1_649_253_955
		},
		{
			'id': 2,
			'entityId': 'im-bot',
			'title': 'Giphy',
			'customData': {
				'imUser': {
					'ID': 2,
					'ACTIVE': true,
					'NAME': 'Giphy',
					'FIRST_NAME': 'Giphy',
					'LAST_NAME': '',
					'WORK_POSITION': 'dumb subtitle',
					'COLOR': '#1eb4aa',
					'AVATAR': '/upload/resize_cache/main/f82/yrc33t95x0offawu6c3puphm8jkxugir/200_200_2/default.png',
					'GENDER': 'M',
					'BIRTHDAY': '',
					'EXTRANET': false,
					'NETWORK': false,
					'BOT': true,
					'CONNECTOR': false,
					'EXTERNAL_AUTH_ID': 'bot',
					'STATUS': 'online',
					'IDLE': false,
					'LAST_ACTIVITY_DATE': false,
					'MOBILE_LAST_DATE': false,
					'ABSENT': false,
					'DEPARTMENTS': [],
					'PHONES': false
				},
				'imBot': {
					'BOT_ID': '2',
					'MODULE_ID': 'imbot',
					'CODE': 'giphy',
					'TYPE': 'B',
					'CLASS': 'Bitrix\\ImBot\\Bot\\Giphy',
					'LANG': null,
					'METHOD_BOT_DELETE': 'onBotDelete',
					'METHOD_MESSAGE_ADD': 'onMessageAdd',
					'METHOD_MESSAGE_UPDATE': '',
					'METHOD_MESSAGE_DELETE': '',
					'METHOD_WELCOME_MESSAGE': 'onChatStart',
					'TEXT_PRIVATE_WELCOME_MESSAGE': '',
					'TEXT_CHAT_WELCOME_MESSAGE': '',
					'COUNT_MESSAGE': '0',
					'COUNT_COMMAND': '0',
					'COUNT_CHAT': '0',
					'COUNT_USER': '1',
					'APP_ID': 'app.56efcaa2980977.85728349',
					'VERIFIED': 'N',
					'OPENLINE': 'N'
				}
			},
			'entityType': 'bot',
			'avatar': '/upload/resize_cache/main/f82/yrc33t95x0offawu6c3puphm8jkxugir/100_100_2/default.png',
			'contextSort': 1_652_358_154,
			'globalSort': 1_647_595_749
		},
		{
			'id': 60,
			'entityId': 'im-bot',
			'title': 'Bitrix24 line',
			'customData': {
				'imUser': {
					'ID': 60,
					'ACTIVE': true,
					'NAME': 'Bitrix24 line',
					'FIRST_NAME': 'Bitrix24 line',
					'LAST_NAME': '',
					'WORK_POSITION': 'some subtitle',
					'COLOR': '#ab7761',
					'AVATAR': '/upload/resize_cache/main/c06/9rhbuybrn3120qsq5xcz32gwbul5snb4/200_200_2/5f20825fdb46aa883ccde5d1fb38b1ee.png',
					'GENDER': 'M',
					'BIRTHDAY': '',
					'EXTRANET': false,
					'NETWORK': true,
					'BOT': true,
					'CONNECTOR': false,
					'EXTERNAL_AUTH_ID': 'bot',
					'STATUS': 'online',
					'IDLE': false,
					'LAST_ACTIVITY_DATE': false,
					'MOBILE_LAST_DATE': false,
					'ABSENT': false,
					'DEPARTMENTS': [],
					'PHONES': false
				},
				'imBot': {
					'BOT_ID': '60',
					'MODULE_ID': 'imbot',
					'CODE': 'network_5332f06b6c647818e4252c7fe9ea06aa',
					'TYPE': 'N',
					'CLASS': 'Bitrix\\ImBot\\Bot\\Network',
					'LANG': null,
					'METHOD_BOT_DELETE': 'onBotDelete',
					'METHOD_MESSAGE_ADD': 'onMessageAdd',
					'METHOD_MESSAGE_UPDATE': 'onMessageUpdate',
					'METHOD_MESSAGE_DELETE': 'onMessageDelete',
					'METHOD_WELCOME_MESSAGE': 'onChatStart',
					'TEXT_PRIVATE_WELCOME_MESSAGE': '',
					'TEXT_CHAT_WELCOME_MESSAGE': '',
					'COUNT_MESSAGE': '0',
					'COUNT_COMMAND': '0',
					'COUNT_CHAT': '0',
					'COUNT_USER': '1',
					'APP_ID': '5332f06b6c647818e4252c7fe9ea06aa',
					'VERIFIED': 'N',
					'OPENLINE': 'N'
				}
			},
			'entityType': 'network',
			'avatar': '/upload/resize_cache/main/c06/9rhbuybrn3120qsq5xcz32gwbul5snb4/100_100_2/5f20825fdb46aa883ccde5d1fb38b1ee.png'
		},
		{
			'id': 64,
			'entityId': 'user',
			'title': 'Fedya Extranet',
			'customData': {
				'name': 'Fedya',
				'lastName': 'Extranet',
				'email': 'fedor_extranet@test.ru',
				'login': 'fedor_extranet@test.ru',
				'imUser': {
					'ID': 64,
					'ACTIVE': true,
					'NAME': 'Fedya Extranet',
					'FIRST_NAME': 'Fedya',
					'LAST_NAME': 'Extranet',
					'WORK_POSITION': '',
					'COLOR': '#4ba5c3',
					'AVATAR': '',
					'GENDER': 'M',
					'BIRTHDAY': '',
					'EXTRANET': true,
					'NETWORK': false,
					'BOT': false,
					'CONNECTOR': false,
					'EXTERNAL_AUTH_ID': 'default',
					'STATUS': 'online',
					'IDLE': false,
					'LAST_ACTIVITY_DATE': '2022-07-09T18:12:31+02:00',
					'MOBILE_LAST_DATE': false,
					'ABSENT': false,
					'DEPARTMENTS': [],
					'PHONES': false
				}
			},
			'tabs': [
				'user'
			],
			'entityType': 'extranet',
			'avatar': ''
		}
	],
	chatModelsData: [
		{
			'dialogId': '25',
			'dialog': {
				'dialogId': '25',
				'chatId': 125,
				'type': 'user',
				'name': 'Andrey Andreev',
				'avatar': '',
				'color': '#3e99ce',
				'extranet': false,
				'counter': 0,
				'userCounter': 0,
				'messageCounter': 0,
				'unreadId': 0,
				'lastMessageId': 0,
				'managerList': [],
				'readList': [],
				'writingList': [],
				'muteList': [],
				'textareaMessage': '',
				'quoteId': 0,
				'editId': 0,
				'owner': 0,
				'entityType': '',
				'entityId': '',
				'dateCreate': null,
				'public': {
					'code': '',
					'link': ''
				}
			},
			'user': {
				'id': 25,
				'name': 'Andrey Andreev',
				'firstName': 'Andrey',
				'lastName': 'Andreev',
				'workPosition': 'accountant',
				'gender': 'M',
				'extranet': false,
				'network': false,
				'bot': false,
				'connector': false,
				'externalAuthId': 'default',
				'status': 'online',
				'idle': false,
				'lastActivityDate': '2022-06-02T06:49:42.000Z',
				'mobileLastDate': false,
				'isOnline': false,
				'isMobileOnline': false,
				'birthday': false,
				'isBirthday': false,
				'absent': false,
				'isAbsent': false,
				'departments': [
					2
				],
				'phones': {
					'workPhone': '',
					'personalMobile': '',
					'personalPhone': '',
					'innerPhone': ''
				}
			}
		},
		{
			'dialogId': 'chat149',
			'dialog': {
				'dialogId': 'chat149',
				'chatId': 149,
				'type': 'chat',
				'name': 'Some accountant chat',
				'avatar': '',
				'color': '#58cc47',
				'extranet': false,
				'counter': 0,
				'userCounter': 2,
				'messageCounter': 0,
				'unreadId': 0,
				'lastMessageId': 0,
				'managerList': [
					1
				],
				'readList': [],
				'writingList': [],
				'muteList': [],
				'textareaMessage': '',
				'quoteId': 0,
				'editId': 0,
				'owner': 1,
				'entityType': '',
				'entityId': '',
				'dateCreate': '2022-05-13T11:58:49.000Z',
				'public': {
					'code': '',
					'link': ''
				}
			}
		},
		{
			'dialogId': 'chat144',
			'dialog': {
				'dialogId': 'chat144',
				'chatId': 144,
				'type': 'chat',
				'name': 'Pink chat',
				'avatar': '',
				'color': '#f76187',
				'extranet': false,
				'counter': 0,
				'userCounter': 3,
				'messageCounter': 0,
				'unreadId': 0,
				'lastMessageId': 0,
				'managerList': [
					1
				],
				'readList': [],
				'writingList': [],
				'muteList': [],
				'textareaMessage': '',
				'quoteId': 0,
				'editId': 0,
				'owner': 1,
				'entityType': '',
				'entityId': '',
				'dateCreate': '2022-04-27T15:05:12.000Z',
				'public': {
					'code': '',
					'link': ''
				}
			}
		},
		{
			'dialogId': '2',
			'dialog': {
				'dialogId': '2',
				'chatId': 110,
				'type': 'user',
				'name': 'Giphy',
				'avatar': 'https://test.ru/upload/resize_cache/main/f82/yrc33t95x0offawu6c3puphm8jkxugir/200_200_2/default.png',
				'color': '#1eb4aa',
				'extranet': false,
				'counter': 0,
				'userCounter': 0,
				'messageCounter': 0,
				'unreadId': 0,
				'lastMessageId': 0,
				'managerList': [],
				'readList': [],
				'writingList': [],
				'muteList': [],
				'textareaMessage': '',
				'quoteId': 0,
				'editId': 0,
				'owner': 0,
				'entityType': '',
				'entityId': '',
				'dateCreate': null,
				'public': {
					'code': '',
					'link': ''
				}
			},
			'user': {
				'id': 2,
				'name': 'Giphy',
				'firstName': 'Giphy',
				'lastName': '',
				'workPosition': 'giphy description',
				'gender': 'M',
				'extranet': false,
				'network': false,
				'bot': true,
				'connector': false,
				'externalAuthId': 'bot',
				'status': 'online',
				'idle': false,
				'lastActivityDate': false,
				'mobileLastDate': false,
				'isOnline': false,
				'isMobileOnline': false,
				'birthday': false,
				'isBirthday': false,
				'absent': false,
				'isAbsent': false,
				'departments': [],
				'phones': {
					'workPhone': '',
					'personalMobile': '',
					'personalPhone': '',
					'innerPhone': ''
				}
			}
		}
	]
};