export type FileInfo = {
	serverId?: number | string,
	type?: string,
	name?: string,
	originalName?: string,
	size?: number,
	width?: number,
	height?: number,
	downloadUrl?: string,
	removeUrl?: string,
	clientPreview?: Blob,
	clientPreviewWidth?: number,
	clientPreviewHeight?: number,
	serverPreviewUrl?: string,
	serverPreviewWidth?: number,
	serverPreviewHeight?: number,
};