<?php

namespace PHPSTORM_META
{

	registerArgumentsSet('bitrix_main_serviceLocator_codes',
		'exceptionHandler',
		'main.validation.service',
	);

	expectedArguments(\Bitrix\Main\DI\ServiceLocator::get(), 0, argumentsSet('bitrix_main_serviceLocator_codes'));

	override(\Bitrix\Main\DI\ServiceLocator::get(0), map([
		'exceptionHandler' => \Bitrix\Main\Diag\ExceptionHandler::class,
		'main.validation.service' => \Bitrix\Main\Validation\ValidationService::class,
	]));

	exitPoint(\Bitrix\Main\Application::end());
	exitPoint(\Bitrix\Main\Application::terminate());
	exitPoint(\CMain::FinalActions());
	exitPoint(\LocalRedirect());

	registerArgumentsSet(
		'bitrix_main_modules_list',
		'abtest',
		'advertising',
		'ai',
		'assistant',
		'b24connector',
		'b24manager',
		'b24network',
		'baas',
		'biconnector',
		'bitrix.eshop',
		'bitrix.giphybot',
		'bitrix.propertiesbot',
		'bitrix.sitecorporate',
		'bitrix24',
		'bitrixcloud',
		'bizcard',
		'bizcardcontroller',
		'bizproc',
		'bizprocdesigner',
		'bizprocmobile',
		'blog',
		'botcontroller',
		'bxtest',
		'calendar',
		'calendarmobile',
		'call',
		'callcontroller',
		'callmobile',
		'catalog',
		'catalogmobile',
		'clouds',
		'cluster',
		'controller',
		'conversion',
		'crm',
		'crmmobile',
		'currency',
		'dav',
		'disk',
		'documentgenerator',
		'documentproxy',
		'extranet',
		'faceid',
		'faceidcontroller',
		'fileman',
		'form',
		'forum',
		'highloadblock',
		'humanresources',
		'iblock',
		'idea',
		'im',
		'imbot',
		'imconnector',
		'imconnectormobile',
		'imconnectorserver',
		'immobile',
		'imopenlines',
		'intranet',
		'intranetmobile',
		'landing',
		'ldap',
		'learning',
		'lists',
		'listsmobile',
		'location',
		'mail',
		'mailcontroller',
		'main',
		'market',
		'meeting',
		'messageservice',
		'microservice',
		'ml',
		'mlserver',
		'mobile',
		'mobileapp',
		'notifications',
		'notificationservice',
		'oauth',
		'osmgateway',
		'perfcheck',
		'perfmon',
		'photogallery',
		'propertiesservice',
		'pull',
		'recyclebin',
		'report',
		'rest',
		'rpa',
		'sale',
		'salescenter',
		'saleservices',
		'scale',
		'search',
		'security',
		'securityscanner',
		'sender',
		'seo',
		'seoproxy',
		'sign',
		'signmobile',
		'signproxy',
		'signsafe',
		'socialnetwork',
		'socialservices',
		'sqs',
		'stafftrack',
		'stafftrackmobile',
		'statistic',
		'storeassist',
		'subscribe',
		'supersetproxy',
		'support',
		'tasks',
		'tasksmobile',
		'timeman',
		'transformer',
		'transformercontroller',
		'translate',
		'ui',
		'up',
		'updateserver',
		'updateserverlight',
		'vote',
		'voximplant',
		'voximplantadmin',
		'voximplantcontroller',
		'webdav',
		'webservice',
		'wiki',
		'workflow',
		'xdimport',
		'xmpp',
		'zoomcontroller',
	);
	expectedArguments(\CModule::IncludeModule(), 0, argumentsSet('bitrix_main_modules_list'));
	expectedArguments(\Bitrix\Main\Loader::includeModule(), 0, argumentsSet('bitrix_main_modules_list'));
	expectedArguments(\Bitrix\Main\Loader::requireModule(), 0, argumentsSet('bitrix_main_modules_list'));
	expectedArguments(\Bitrix\Main\ModuleManager::isModuleInstalled(), 0, argumentsSet('bitrix_main_modules_list'));
	expectedArguments(\Bitrix\Main\Config\Option::get(), 0, argumentsSet('bitrix_main_modules_list'));
	expectedArguments(\Bitrix\Main\Config\Option::set(), 0, argumentsSet('bitrix_main_modules_list'));
	expectedArguments(\Bitrix\Main\Config\Configuration::getInstance(), 0, argumentsSet('bitrix_main_modules_list'));
	expectedArguments(\Bitrix\Main\DI\ServiceLocator::registerByModuleSettings(), 0, argumentsSet('bitrix_main_modules_list'));
}